import type { Translations } from './types';
import { en } from './en';

export const fr: Translations = {
  ...en,
  baseCurrency: { TWD: 'Dollar taïwanais', USD: 'Dollar américain', JPY: 'Yen japonais', EUR: 'Euro', GBP: 'Livre sterling', HKD: 'Dollar HK', KRW: 'Won coréen', CAD: 'Dollar canadien', INR: 'Roupie indienne', CNY: 'Yuan chinois', AUD: 'Dollar australien', SAR: 'Riyal saoudien', BRL: 'Réal brésilien' },
  common: { ...en.common, confirm: 'Confirmer', cancel: 'Annuler', delete: 'Supprimer', edit: 'Modifier', save: 'Enregistrer', close: 'Fermer', loading: 'Chargement...', search: 'Rechercher', logoutConfirm: 'Déconnexion ?', baseCurrency: 'Devise de base', upgrade: 'Mettre à niveau', footerLocalDataPrivacy: 'Toutes les données de transaction sont stockées localement sur votre appareil pour protéger votre vie privée.' },
  nav: { dashboard: 'Tableau de bord', history: 'Historique', funds: 'Fonds', accounts: 'Comptes', rebalance: 'Rééquilibrage', simulator: 'Simulateur', splits: 'Splits', help: 'Aide', logout: 'Déconnexion' },
  pages: { ...en.pages, dashboard: 'Portefeuille', history: 'Historique (transactions et flux)', funds: 'Gestion des fonds', accounts: 'Comptes', rebalance: 'Rééquilibrage', simulator: 'Simulateur d\'allocation', splits: 'Gestion des splits', help: 'Paramètres et sauvegarde' },
  stockSplit: {
    title: 'Gestion des splits d\'actions',
    hint: 'Les transactions conservent les quantites et prix saisis a l\'epoque. Les evenements de split ajustent automatiquement les positions et le P/L a partir de la date d\'effet. Si les transactions apres cette date utilisent deja les quantites post-split, ne l\'enregistrez pas deux fois.',
    ticker: 'Code boursier',
    tickerPlaceholder: 'ex. 2330, AAPL',
    market: 'Marche',
    effectiveDate: 'Date d\'effet',
    sharesFrom: 'Actions avant split',
    sharesTo: 'Actions apres split',
    splitRatio: 'Ratio de split',
    note: 'Remarque',
    notePlaceholder: 'ex. Split d\'actions en janvier 2024',
    addButton: 'Ajouter un evenement de split',
    listTitle: 'Splits configures',
    totalCount: '{count} enregistrements au total',
    emptyList: 'Aucun evenement de split',
    tickerRequired: 'Veuillez saisir un ticker',
    dateRequired: 'Veuillez selectionner une date d\'effet',
    invalidRatio: 'Le nombre d\'actions avant/apres split doit etre un entier positif',
    duplicateError: 'Un evenement existe deja pour le meme ticker, marche et date d\'effet',
    addSuccess: 'Evenement de split ajoute',
    deleteSuccess: 'Evenement de split supprime',
    deleteConfirmTitle: 'Confirmer la suppression du split',
    deleteConfirmMessage: 'Supprimer l\'evenement de split de {ticker} ({date}) ?',
  },
  login: { title: 'Connexion TradeView', subtitle: 'Gestionnaire d\'actifs d\'investissement', email: 'E-mail', password: 'Mot de passe', login: 'Connexion', privacy: 'Confidentialité', privacyDesc: 'Données stockées localement. Aucune collecte de données personnelles.', riskDisclaimer: 'Avertissement', riskDisclaimerDesc: 'Les investissements comportent des risques. Les performances passées ne garantissent pas les résultats futurs.' },
  dashboard: {
    ...en.dashboard,
    netCost: 'Investi net',
    totalAssets: 'Actif total',
    totalPL: 'Gain/Perte',
    annualizedReturn: 'Rendement annualisé (XIRR)',
    detail: 'Détail',
    includeCash: 'Incl. Espèces',
    detailedStatistics: 'Statistiques Détaillées',
    totalCost: 'Coût Total',
    totalPLAmount: 'Montant Total Gain/Perte',
    accumulatedCashDividends: 'Dividendes en Espèces Accumulés',
    accumulatedStockDividends: 'Dividendes en Actions Accumulés',
    yearDividendTaxTitle: 'Retenues liees aux dividendes (annee en cours, indicatif)',
    yearWithheldNhi: 'Supplement NHI taiwanais retenu (somme des lignes renseignees)',
    yearUsWithholding: 'Retenue a la source US sur dividendes (saisie, sinon estimation a 30 % depuis le net)',
    yearUsWithholdingHint: 'Renseignez « retenue US » dans les lignes de dividendes en especes pour obtenir un total precis.',
    annualizedReturnRate: 'Taux de Rendement Annualisé',
    avgExchangeRate: 'Taux de Change Moyen (TWD/USD)',
    currentExchangeRate: 'Taux de Change Actuel',
    totalReturnRate: 'Taux de Rendement Total',
    assetVsCostTrend: 'Tendance Actifs vs Coût',
    assetTrendMergedSubtitle:
      'Barres principales a gauche : cout investi cumule et P/L ; courbes bleue/orange : actif total et estimation ; fines barres a droite : flux annuels entrants/sortants, P/L de marche et dividendes.',
    toggleYearlyFlowBars: 'Barres de flux annuels',
    yearlyFlowIn: 'Entrees annuelles',
    yearlyFlowOut: 'Sorties annuelles',
    yearlyMarketPL: 'P/L de marche annuel',
    yearlyIncome: 'Dividendes/Interets annuels',
    aiCorrectHistory: 'IA Corriger les Actifs Historiques',
    marketDistribution: 'Poids par ticker',
    allocation: 'Repartition',
    allocationDonutSubtitle:
      'Anneau extérieur : chaque ligne (ex. VT) en % des positions / Anneau intérieur : actions/obligations (hors cash)',
    stockBondRatioBadge: 'Actions / obligations',
    legendMarketOuter: 'Positions par ticker (extérieur)',
    legendStockBondInner: 'Actions/obligations (intérieur)',
    assetClassOverrideTitle: 'Classification actions/obligations personnalisée (remplacements)',
    tickerSymbolLabel: 'Code ticker',
    tickerPlaceholderExamples: 'ex. AGG / TLT / BND',
    assetClassSelectLabel: 'Classe',
    equityLabelShort: 'Actions',
    bondLabelShort: 'Obligations',
    saveAssetClassOverride: 'Enregistrer',
    clearTickerOverride: 'Effacer',
    currentOverridesHeading: 'Remplacements actifs',
    removeOverrideTitle: 'Cliquer pour retirer',
    annualPerformance: 'Performance Annuelle',
    year: 'Année',
    startAssets: 'Actifs de Début',
    annualNetInflow: 'Afflux Net Annuel',
    endAssets: 'Actifs de Fin',
    annualProfit: 'Profit Annuel',
    annualROI: 'ROI Annuel',
    brokerageAccounts: 'Liste des comptes',
    accountName: 'Nom du compte',
    totalAssetsNT: 'Actifs Totaux',
    marketValueNT: 'Valeur Marchande',
    balanceNT: 'Solde / Dette',
    balanceColumnTooltip:
      'Courtage : solde de trésorerie ; passif : capital dû.',
    profitNT: 'Resultat',
    profitFormulaTooltip: 'P/L total = Non realise + Realise + Div./Interets. Le realise ne compte que les SELL, les transferts sont exclus.',
    accountReturnRateTooltip:
      'Rendement cumule = P/L ÷ denominateur. Encaisse nette ; si ≤ 0 cout cumule. Transfert avec valeur de marche : realise source, cout cible. Sans position et cash ≈ 0 = cloture ; sans position avec cash = flat.',
    accountClosedBadge: 'Cloture',
    accountFlatBadge: 'Sans position',
    unrealizedPL: 'P/L non realise',
    realizedPL: 'P/L realise',
    dividendInterest: 'Div./Interets',
    displayCurrency: 'Devise d\'Affichage',
    ntd: 'Dollar taïwanais',
    usd: 'Dollar américain',
    portfolioHoldings: 'Positions du Portefeuille',
    mergedDisplay: 'Regroupé (Par Symbole)',
    detailedDisplay: 'Détaillé (Par Compte)',
    aiUpdatePrices: 'IA Mettre à Jour les Prix et Taux de Change',
    estimatedGrowth8: 'Est. Croissance 8%',
    annualizedReturnTarget8: 'Objectif 8 %',
    chartLoading: 'Chargement du graphique...',
    noChartData: 'Veuillez d\'abord ajouter des dépôts de fonds et des transactions',
    noHoldings: 'Aucune position',
    noAccounts: 'Aucun compte de courtage. Veuillez ajouter des comptes dans Comptes.',
    costBreakdown: 'Répartition du Coût d\'Investissement Net',
    netInvestedBreakdown: 'Répartition de l\'Investissement Net',
    calculationFormula: 'Formule: Investissement Net = Dépôts - Retraits',
    formulaNote: 'Note: Pour les comptes USD, le taux de change historique est utilisé s\'il est disponible, sinon le taux actuel des paramètres. Les transferts et intérêts ne sont pas inclus dans le coût.',
    attention: 'Remarque',
    date: 'Date operation',
    category: 'Categorie',
    originalAmount: 'Montant d\'origine',
    twdCost: 'Cout ({currency})',
    totalNetInvested: 'Total',
    deposit: 'Dépôt(+)',
    withdraw: 'Retrait(-)',
    fixedTWD: 'Montant TWD fixe',
    historicalRate: 'Taux historique',
    currentRate: 'Taux actuel',
    taiwanDollar: 'Dollar taiwanais',
    twdIncludesFee: 'TWD (frais inclus)',
    aiAdvisor: 'Conseiller Gemini IA',
    aiAdvisorDesc: 'Analyse de Portefeuille',
    notInvestmentAdvice: 'Pas un conseil en investissement.',
    chartLabels: {
      investmentCost: 'Coût d\'Investissement',
      accumulatedPL: 'Gain/Perte Accumulé',
      estimatedAssets: 'Est. Actifs Totaux (8%)',
      totalAssets: 'Actifs Totaux',
      toDate: ' à ce jour',
      realData: ' (Prix Réel)',
      estimated: ' (Estimé)',
      profit: 'Gain',
      loss: 'Perte',
      barName: 'Gain/Perte Accumulé: Vert=Gain Rouge=Perte',
      yearlyPeriodRoi: 'Rendement annuel',
      chartLegendYearlyPeriodRoi:
        'Ligne rose (axe droit %) : un point par an au T4 (année en cours : « à ce jour » si pas de T4). Comme le tableau annuel.',
    },
    noHoldingsData: 'Aucune donnée de positions',
    realHistoricalData: 'Données historiques réelles',
    formulaLabel: 'Formule: ',
    aiCorrectHistoryTitle: 'Modifier manuellement ou utiliser l\'IA pour corriger les prix historiques',
    startAnalysis: 'Démarrer l\'Analyse',
    analyzing: 'Analyse en cours...',
    viewCalculationDetails: 'Voir les Détails',
    riskWarning: 'Avertissement de Risque',
    riskWarningDesc: 'Les investissements comportent des risques. Les performances passées ne garantissent pas les résultats futurs.',
    chartLegendQuarterSnapshot: '✅ Snapshot fin de trimestre (données Yahoo)',
    chartLegendLinearInterpolation:
      '⚠️ Interpolation linéaire — ouvrez Prix historiques pour récupérer les données manquantes',
    netWorth: 'Patrimoine net',
    totalDebt: 'Dette totale',
    leverageNetInvestedNote: 'Investi net peut inclure des tirages de crédit (~{amount})',
    leverageXirrWarning: 'XIRR inclut des fonds empruntés — interpréter avec prudence',
    debtDisbursement: 'Tirage crédit',
    debtRepayment: 'Remboursement crédit',
    leverageFormulaNote: 'Tirages/remboursements (passif↔courtage) comptent dans investi net et XIRR. Intérêts d\'emprunt non.',
    debtAccountsTitle: 'Crédit & passif',
    creditUsedOfLimit: 'Emprunté {used} / plafond {limit} ({percent}% d\'utilisation)',
    estimatedMonthlyInterest: 'Intérêts estimés mois prochain',
    estimatedMonthlyInterestNote: 'Estimation selon solde actuel et taux annuel (un mois)',
  },
  marketChart: {
    title: 'Performance par Marché',
    subtitle: 'Rendement cumulé et pondération par marché',
    cumulativeReturn: 'Rendement cumulé',
    weight: 'Pondération',
    value: 'Valeur',
    cumulativeReturnShort: 'Rend.',
    weightShort: 'Poids',
    valueShort: 'Valeur',
    noData: 'Aucune position',
    ratio: 'Part',
  },
  waterfall: {
    title: 'Cascade de Flux de Trésorerie',
    subtitle: 'Valeur nette cumulée : entrées, P&L, dividendes, sorties',
    byYear: 'Par Année',
    byQuarter: 'Par Trimestre',
    deposit: 'Entrées',
    withdraw: 'Sorties',
    stockPL: 'P&L Actions',
    dividend: 'Dividendes',
    net: 'Net Période',
    runningTotal: 'Cumulé',
    periodNet: 'Net de periode',
    noData: 'Aucun flux de trésorerie',
    plPositive: 'P&L Actions (+)',
    plNegative: 'P&L Actions (−)',
    legendHintStart: 'Valeur totale du portefeuille (dont liquidités) en début de période.',
    legendHintInflow: 'Dépôts moins retraits sur la période. Bleu = flux net entrant, orange = sortant.',
    legendHintDividend: 'Dividendes en espèces et intérêts crédités sur la période.',
    legendHintPL: 'Variation d’actifs hors flux net et revenus ; P&L de marché approximatif. Vert = gain, rouge = perte.',
    includingLabel: '(y compris {item})',
  },
  dividendHeatmap: {
    title: 'Carte Thermique Dividendes',
    subtitle: 'Chaque cellule = dividende mensuel. Plus foncé = plus élevé.',
    totalDividend: 'Total Dividendes',
    noData: 'Aucun dividende en espèces',
    bestMonth: 'Meilleur mois',
    less: 'Moins',
    more: 'Plus',
    monthlyBreakdown: 'Détail Mensuel',
    yearTotal: 'Année',
    monthTotal: 'Mois',
    recordedLabel: 'Enregistre',
    pendingLabel: 'A completer',
  },
  dividendTax: {
    twTooltipTitle: 'Estimation fiscale (indicative)',
    estSinglePayout: 'Versement unique estime (dernier dividende/action x quantite)',
    estNhiFee: 'Supplement NHI estime (2,11 %, indicatif)',
    splitHint0050: 'Si la distribution est repartie entre plusieurs courtiers/organismes payeurs, le seuil peut varier par versement ; la retenue depend de l\'organisme payeur.',
    usNetTooltipTitle: 'Retenue a la source sur dividendes US (indicative)',
    marketWithholdingRef: 'Retenue a la source sur dividendes (estimation)',
    estGrossPerPayout: 'Brut estime par versement (par action x quantite)',
    estNetAfterWithholding: 'Net estime apres retenue (~30 %, soit ~70 % restants)',
    upcomingTitle: 'Ex-dividendes prevus dans les 90 prochains jours (Yahoo)',
    upcomingSubtitle: 'Montant estime via « dernier dividende en especes par action x positions actuelles », pouvant differer du reel.',
    upcomingEmpty: 'Aucune date ex-dividende admissible pour le moment, ou donnees publiques indisponibles.',
    upcomingExDate: 'Date ex-dividende',
    upcomingInferredMonthHint:
      'Le « mois estime » est derive des mois ex-dividende des annees recentes et ignore les mois deja enregistres cette annee ; Yahoo ne fournit actuellement pas de date ex-dividende confirmee dans les 90 prochains jours (date affichee « — »). Le montant reste estime via « dernier dividende en especes par action x positions actuelles » et ne constitue pas une annonce officielle.',
    upcomingEstTwd: 'Dividende estime (TWD)',
    upcomingEstUsd: 'Net estime (USD)',
    dataFromYahoo: 'Source : Yahoo Finance (cache local)',
    disclaimerShort: 'A titre indicatif uniquement ; pas un conseil fiscal ou juridique.',
    usBadgeShort: 'env. 70 %',
    nhiForecastTag: 'Le versement unique estime peut declencher le supplement NHI',
    pendingActualTitle: 'Dividendes reels a confirmer',
    pendingActualSubtitle: 'Ex-dividendes de cette annee absents de vos transactions sont listes ci-dessous. « Ajouter » enregistre a la date de versement (visible sur la heatmap) ; « Masquer » masque la ligne.',
    pendingActualDripHint: 'Pour le réinvestissement des dividendes (DRIP), utilisez « Ajouter une transaction » dans l\'historique — n\'appuyez pas sur « Ajouter » ici.',
    pendingActualEmpty: 'Aucun dividende reel a completer pour le moment.',
    pendingActualLoading: 'Chargement des donnees reelles...',
    pendingActualAddBtn: 'Ajouter',
    pendingActualAddCol: 'Ajouter aux transactions',
    pendingActualDismissBtn: 'Masquer',
    pendingActualToggleHide: 'Masquer la liste',
    pendingActualToggleShow: 'Afficher la liste',
    pendingActualEstimatedDate: 'Date de versement estimee',
    pendingActualSourceMoneyDj: 'Donnees reelles',
    pendingActualSourceYahoo: 'Complements Yahoo',
    pendingActualPayDate: 'Date de versement',
    pendingActualPerShare: 'Dividende par action',
    pendingActualEstAmount: 'Net estime (apres impots)',
    pendingActualAccount: 'Compte credite',
    pendingActualNoteTemplate: 'Import auto : {perShare} par action, {qty} actions',
    pendingActualConfirmGrossAmount: 'Montant brut (avant impôt)',
    pendingActualCompositionEstimated: 'Part officielle estimée soumise à la NHI (dividendes {dividend}% + intérêts {interest}%)',
    pendingActualNhiEligibleIncome: 'Revenu estimé soumis à la NHI',
    pendingActualCompositionWarning: 'La composition est une estimation FundClear ; l’avis de distribution fait foi.',
    pendingActualCompositionUnavailable: 'Composition officielle indisponible ; aucun prélèvement NHI n’a été déduit automatiquement.',
    pendingActualWireFeeOption: 'Déduire 10 TWD de frais de virement',
    pendingActualWireFeeHint: 'Les frais varient selon le courtier/la banque ; activez seulement si le versement les a déduits.',
    pendingActualWireFeeLabel: 'Frais de virement',
  },
  funds: { 
    ...en.funds, 
    title: 'Gestion des fonds',
    operations: 'Opérations',
    clearAll: 'Effacer les fonds filtrés',
    batchImport: 'Import en lot',
    addRecord: '+ Ajouter un enregistrement',
    filter: 'Filtrer',
    clearFilters: 'Effacer tous les filtres',
    accountFilter: 'Compte',
    typeFilter: 'Filtre par type',
    dateFrom: 'Date de début',
    dateTo: 'Date de fin',
    allAccounts: 'Tous les comptes',
    allTypes: 'Tous les types',
    deposit: 'Dépôt', 
    withdraw: 'Retrait', 
    transfer: 'Virement', 
    interest: 'Intérêts',
    loanInterest: 'Intérêts d\'emprunt',
    showRecords: 'Affichage de {count} enregistrements',
    totalRecords: 'Total de {total}',
    last30Days: '30 derniers jours',
    thisYear: 'Cette année',
    confirmClearAll: 'Confirmer l\'effacement des enregistrements de fonds filtrés ?',
    confirmClearAllMessage: 'Cette opération supprimera {count} enregistrement(s) de dépôt, retrait, virement et intérêts dans le filtre actuel, et ne peut pas être annulée. Il est recommandé de sauvegarder d\'abord vos données.',
    confirmClear: 'Confirmer l\'effacement',
  },
  history: {
    tabTransactions: 'Historique des transactions',
    tabTimeline: 'Chronologie de détention',
    operations: 'Opérations',
    batchUpdateMarket: 'Mise à jour groupée des marchés',
    clearAll: 'Effacer les transactions filtrées',
    batchImport: 'Import groupé',
    addRecord: '+ Ajouter un enregistrement',
    filter: 'Filtrer',
    accountFilter: 'Filtrer par compte',
    tickerFilter: 'Filtrer par symbole',
    dateFrom: 'Date de début',
    dateTo: 'Date de fin',
    includeCashFlow: 'Inclure les enregistrements de flux de trésorerie',
    clearFilters: 'Effacer tous les filtres',
    showingRecords: 'Affichage de {count} enregistrements',
    totalRecords: 'Total {total} : {transactionCount} transactions{hasCashFlow}',
    last30Days: '30 derniers jours',
    thisYear: 'Cette année',
    noTransactions: 'Aucune transaction',
    noMatchingTransactions: 'Aucune transaction correspondante trouvée',
    edit: 'Modifier',
    delete: 'Supprimer',
    includeCashFlowDesc: 'Cocher pour afficher les dépôts, retraits, virements, etc. pour voir l\'évolution du solde',
    hiddenCashFlowRecords: '{count} enregistrements de flux de trésorerie masqués',
    cashFlowDeposit: 'Dépôt',
    cashFlowWithdraw: 'Retrait',
    cashFlowTransfer: 'Virement sortant',
    cashFlowTransferIn: 'Virement entrant',
  },
  stockTimeline: {
    ...en.stockTimeline,
    noTransactionsHint: 'Aucune transaction pour le moment. Ajoutez d\'abord une transaction.',
    searchPlaceholder: 'Rechercher un ticker...',
    allMarkets: 'Tous les marchés',
    statusAll: 'Tous',
    statusHolding: 'En portefeuille',
    statusClosed: 'Clôturé',
    sortByFirstBuy: 'Trier par premier achat',
    sortByTicker: 'Trier par ticker',
    sortByPLPercent: 'Trier par P/L %',
    countUnit: 'titres',
    symbol: 'Titre',
    plAndStatus: 'P/L / Statut',
    holdingTitle: 'En portefeuille',
    closedTitle: 'Clôturé',
    firstBuy: 'Premier achat',
    lastTrade: 'Dernière transaction',
    holdingDays: 'Jours de détention',
    avgCost: 'Coût moyen',
    currentPrice: 'Prix actuel',
    holdingQty: 'Quantité',
    pl: 'Gain/Perte',
    fee: 'Frais',
    noMatches: 'Aucun titre ne correspond aux filtres',
    legendBuy: 'Achat',
    legendSell: 'Vente',
    legendStockDividend: 'Div. actions',
    legendCashDividend: 'Div. cash',
    legendTransferIn: 'Transfert entrant',
    legendTransferOut: 'Transfert sortant',
    legendHolding: 'En portefeuille',
  },
  labels: { ...en.labels, date: 'Date op.', account: 'Compte', amount: 'Montant', balance: 'Solde', action: 'Opération', type: 'Type d\'ordre', price: 'Prix', quantity: 'Quantité', currency: 'Devise', fee: 'Frais', exchangeRate: 'Taux', totalCost: 'Coût total', category: 'Catégorie', description: 'Symbole/Description', note: 'Remarque' },
  holdings: {
    ...en.holdings,
    portfolioHoldings: 'Positions',
    mergedDisplay: 'Regroupé par symbole',
    detailedDisplay: 'Détail par compte',
    aiUpdatePrices: 'MAJ prix et taux (IA)',
    aiSearching: 'Recherche IA...',
    market: 'Marché',
    ticker: 'Symbole',
    quantity: 'Quantité',
    currentPrice: 'Prix actuel',
    weight: 'Pondération',
    cost: 'Coût total',
    marketValue: 'Valeur de marché',
    profitLoss: 'G/P',
    annualizedROI: 'Rendement annualisé',
    dailyChange: 'Variation journalière',
    avgPrice: 'Prix moy.',
    noHoldings: 'Aucune position. Ajoutez des transactions.',
  },
  accounts: { 
    ...en.accounts, 
    addAccount: 'Ajouter un compte brokerage/banque', 
    accountName: 'Nom du compte',
    accountNamePlaceholder: 'ex. Fubon Securities, Firstrade',
    currency: 'Devise', 
    currencyTWD: 'Dollar taiwanais',
    currencyUSD: 'Dollar americain',
    currencyJPY: 'Yen japonais',
    currencyEUR: 'Euro',
    currencyGBP: 'Livre sterling',
    currencyHKD: 'Dollar de Hong Kong',
    currencyKRW: 'Won sud-coreen',
    currencyCNY: 'Yuan chinois',
    currencyINR: 'Roupie indienne',
    currencyCAD: 'Dollar canadien',
    currencyAUD: 'Dollar australien', 
    currencySAR: 'Riyal saoudien', 
    currencyBRL: 'Real brésilien',
    subBrokerage: 'Courtier étranger',
    add: 'Ajouter', 
    update: 'Mettre à jour', 
    editAccount: 'Modifier le compte',
    balance: 'Solde', 
    cancel: 'Annuler',
    updateAccount: 'Mettre à jour le compte',
    confirmDelete: 'Confirmer la suppression du compte',
    confirmDeleteMessage: 'Êtes-vous sûr de vouloir supprimer "{name}"?',
    deleteWarning: 'Note : Cela ne supprimera pas les enregistrements de transactions historiques pour ce compte, mais peut causer des problèmes lors du filtrage.',
    deleteAccount: 'Confirmer la suppression',
    cannotDeleteClosedTitle: 'Impossible de supprimer un compte clôturé',
    cannotDeleteClosedMessage:
      'Ce compte n’a plus de positions ni de liquidités. La suppression orphelinerait l’historique. Pour le retirer de la liste, masquez-le.',
    hideAccount: 'Masquer le compte',
    hiddenAccountsSection: 'Comptes masqués',
    restoreAccount: 'Rétablir',
    duplicateHiddenNameHint:
      'Le nom « {name} » correspond à un compte masqué. Rétablissez-le d’abord, ou choisissez un autre nom.',
    noAccounts: 'Aucun compte pour le moment. Veuillez ajouter votre premier compte brokerage ci-dessus.',
    cashBalance: 'Solde en espèces',
    editAccountTitle: 'Modifier le compte',
    accountKind: 'Type de compte',
    accountKindBrokerage: 'Courtage (investissement)',
    accountKindLiability: 'Passif (dette)',
    debtKind: 'Type de crédit',
    debtKindPersonal: 'Prêt personnel',
    debtKindMortgage: 'Hypothèque',
    debtKindSecurities: 'Crédit titres',
    annualInterestRate: 'Taux annuel (%)',
    creditLimit: 'Plafond de crédit',
    linkedBrokerageAccount: 'Courtage lié',
    debtBalance: 'Principal dû',
    liabilityHint: 'Tirage : virement passif → courtage uniquement.',
  },
  debt: {
    paymentAlertTitle: 'Rappel échéance crédit',
    paymentAlertBody: '« {name} » échéance dans {days} jour(s) ({date}), env. {amount}. Vérifier le solde.',
    acknowledgePaid: 'Marquer comme payé',
    remindLater: 'Rappeler plus tard',
    spreadDangerTitle: 'Alerte marge négative',
    spreadWarningTitle: 'Alerte marge faible',
    spreadBody: '« {name} » rendement {ret}% vs coût crédit {rate}% (sous marge de sécurité).',
    notAdvice: 'À titre indicatif uniquement, pas un conseil en investissement.',
    leverageNetNote: 'Investi net peut inclure emprunt (~{amount}). Interpréter les rendements à part.',
  },
  rebalance: { 
    ...en.rebalance, 
    title: 'Rééquilibrage', 
    resetToCurrent: 'Réinitialiser aux poids actuels',
    totalAssets: 'Actif total (incl. espèces)',
    enable: 'Activer',
    symbol: 'Symbole',
    currentPrice: 'Prix actuel',
    currentValue: 'Valeur actuelle',
    currentWeight: 'Poids actuel',
    targetWeight: 'Poids cible',
    targetValue: 'Valeur cible',
    adjustAmount: 'Montant d\'ajustement',
    suggestedAction: 'Action suggérée',
    cash: 'Espèces',
    totalEnabled: 'Éléments activés',
    remainingFunds: 'Fonds restants',
    notParticipating: 'Ne participe pas',
    accounts: ' comptes',
    description: 'Description :',
    description1: 'Les actions portant le même nom sont automatiquement fusionnées et affichées. Les poids cibles sont alloués proportionnellement à chaque compte en fonction des valeurs actuelles.',
    description2: 'Cochez la colonne "Activer" pour sélectionner les actions/obligations à rééquilibrer. Les éléments non cochés ne participeront pas aux calculs de rééquilibrage.',
    description3: 'Les espèces peuvent également être cochées. Si cochées, vous pouvez définir manuellement le pourcentage cible d\'espèces ; si non cochées, les espèces resteront inchangées.',
    description4: 'Les poids cibles sont automatiquement enregistrés. Si l\'objectif d\'espèces n\'est pas défini manuellement, le système calculera automatiquement et allouera le pourcentage restant aux espèces ; s\'il est défini manuellement, votre valeur spécifiée sera utilisée.',
    description5: 'Si le pourcentage cible "Espèces" est négatif, cela signifie que votre allocation cible d\'actions dépasse 100%. Veuillez réduire certains pourcentages cibles d\'actions.',
    description6: 'Cliquez sur "Réinitialiser aux poids actuels" pour réinitialiser rapidement toutes les valeurs cibles à l\'état actuel.',
    buy: 'Acheter', 
    sell: 'Vendre',
    accountLabel: '(Compte)',
    sharesLabel: '(Actions)',
    totalLabel: 'Total general (',
    accountCount: ' comptes',
  },
  simulator: { 
    ...en.simulator, 
    title: 'Simulateur d\'allocation', 
    description: 'Cet outil vous permet de comparer les rendements attendus de différentes allocations d\'actifs. Entrez les taux de rendement annualisés depuis la création pour diverses actions ou ETF comme hypothèses, et le système calculera la performance attendue de votre portefeuille en fonction de vos ratios d\'allocation.',
    descriptionWarning: '⚠️ Note : Les performances passées ne garantissent pas les résultats futurs. Cette simulation est à titre de référence uniquement.',
    basicSettings: 'Paramètres de base',
    initialAmount: 'Montant d\'investissement initial',
    investmentYears: 'Années d\'investissement',
    regularInvestment: 'Investissement régulier (optionnel)',
    regularAmount: 'Montant de l\'investissement régulier',
    frequency: 'Fréquence d\'investissement',
    monthly: 'Mensuel',
    quarterly: 'Trimestriel',
    yearly: 'Annuel',
    annualTotal: 'Investissement total annuel',
    setToZero: 'Définir à 0 pour désactiver l\'investissement régulier',
    importFromHoldings: 'Importer depuis les positions existantes',
    importButton: 'Importer depuis les positions existantes',
    manualAdd: 'Ajouter un actif manuellement',
    ticker: 'Symbole d\'action',
    tickerPlaceholder: 'ex. 0050',
    market: 'Marché',
    marketTW: 'Taïwan (TW)',
    marketUS: 'États-Unis (US)',
    marketUK: 'Royaume-Uni (UK)',
    marketJP: 'Japon (JP)',
    marketCN: 'Chine (CN)',
    marketSZ: 'Chine Shenzhen (SZ)',
    marketIN: 'Inde (IN)',
    marketCA: 'Actions canadiennes (CA)',
    marketFR: 'Actions francaises (FR)',
    marketHK: 'Actions de Hong Kong (HK)',
    marketKR: 'Corée du Sud (KR)',
    marketDE: 'Allemagne (DE)',
    marketAU: 'Australie (AU)',
    marketSA: 'Arabie saoudite (SA)',
    marketBR: 'Brésil (BR)',
    annualReturn: 'Rendement annualisé (%)',
    allocation: 'Repartition (%)',
    add: 'Ajouter',
    addRow: 'Ajouter une ligne',
    action: 'Operation',
    delete: 'Supprimer',
    addAll: 'Ajouter à la liste',
    yearlyInvestment: 'Investissement annuel',
    autoQuery: '🔍 Requête automatique',
    autoQueryTitle: 'Requête automatique du rendement annualisé depuis l\'introduction en bourse',
    querying: 'Requête en cours',
    cagrExplanation: '📊 Explication du calcul du rendement annualisé :',
    cagrFormulaDesc: 'Le système utilise la formule CAGR (Taux de croissance annuel composé) :',
    cagrFormula: 'CAGR = ((Prix actuel / Prix initial) ^ (1 / Années)) - 1',
    cagrExample: 'Cela représente le taux de rendement composé moyen par an si acheté lors de l\'introduction en bourse et détenu jusqu\'à présent.',
    cagrExampleValue: 'Exemple : L\'action passe de 100 à 200 sur 5 ans, le rendement annualisé est d\'environ 14,87%',
    assetList: 'Liste des allocations d\'actifs',
    autoBalance: 'Equilibrage automatique',
    clearAll: 'Tout effacer',
    allocationSum: 'Somme des repartitions :',
    totalInvested: 'Total investi',
    finalValue: 'Valeur finale',
    totalReturn: 'Rendement total',
    portfolioAnnualReturn: 'Rendement annualise du portefeuille',
    initial: 'Capital initial',
    yearlyProjection: 'Projection annuelle',
    yearlyReturnAnalysis: 'Analyse des rendements annuels',
    detailedYearlyProjection: 'Projection annuelle detaillee',
    year: 'Annee',
    assetValue: 'Valeur des actifs',
    yearlyReturn: 'Rendement annuel',
    cumulativeInvestment: 'Investissement cumule',
    yearlyReturnRate: 'Taux de rendement annuel',
    allocationWarning: '⚠️ La somme des repartitions doit etre egale a 100 %, actuellement',
    confirmClear: 'Confirmer l\'effacement',
    confirmClearMessage: 'Voulez-vous vraiment effacer toutes les allocations d\'actifs ? Cette action est irreversible.',
    dataWarning: '⚠️ Avertissement d\'integrite des donnees :',
    dataWarningDesc:
      'Conseil : si les resultats sont nettement inferieurs aux attentes, les donnees historiques Yahoo Finance peuvent etre incompletes. Verifiez avec des sources officielles ou saisissez manuellement un rendement annualise plus precis.',
    errorEnterTicker: 'Veuillez saisir un ticker',
    errorEnterAllocation: 'Veuillez saisir la repartition',
    errorAllocationRange: 'La repartition doit etre comprise entre 0 % et 100 %',
    errorAllocationSum: 'La somme des repartitions ne peut pas depasser 100 %',
    errorNoHoldings: 'Aucune position disponible a importer',
    errorEnterTickerFirst: 'Veuillez d\'abord saisir un ticker',
    errorCannotGetReturn: 'Impossible d\'obtenir le rendement annualise de {ticker}, veuillez le saisir manuellement',
    errorQueryFailed: 'Echec de la requete du rendement annualise, veuillez le saisir manuellement',
    close: 'Fermer',
    cancel: 'Annuler',
    yearPrefix: 'Annee',
    yearSuffix: ' an',
    queryingReturn: 'Requete du rendement annualise pour {ticker}...',
  },
  help: {
    dataManagement: 'Gestion des données',
    export: 'Exporter',
    exportDesc: 'Exporter transactions, comptes et cours en JSON. Sauvegardes régulières recommandées.',
    downloadBackup: 'Télécharger la sauvegarde (.json)',
    import: 'Importer',
    importWarning: 'Attention : importer un fichier remplace toutes les données actuelles.',
    uploadBackup: 'Envoyer un fichier de sauvegarde',
    authorizedUsers: 'Utilisateurs autorisés',
    authorizedUsersDesc: 'E-mails pouvant se connecter sans mot de passe (masqués pour la confidentialité) :',
    emailAccount: 'E-mail',
    status: 'Statut',
    systemAuthorized: 'Autorisé par le système',
    contact: 'Autorisation d\'achat et contact administrateur',
    contactTitle: 'Vous aimez ce système ?',
    contactDesc: 'Non-membre souhaitant des droits d\'usage permanents, ou suggestions/bugs : contactez le développeur. Réponses parfois lentes.',
    contactEmail: 'Contacter l\'administrateur (e-mail)',
    subscription: 'Abonnement membre (achat intégré)',
    subscriptionTitle: 'Devenir membre / Gérer l\'abonnement',
    subscriptionDesc: 'Abonnez-vous via l\'App Store pour débloquer toutes les fonctionnalités. Consultez les offres, achetez ou restaurez vos achats ici.',
    subscribeButton: 'Ouvrir les offres d\'abonnement',
    deleteAppAccount: 'Supprimer le compte et les données',
    deleteAppAccountDesc: 'Efface définitivement l\'état de connexion et toutes les données locales sur cet appareil. Irréversible. Pour annuler l\'abonnement : Réglages → Abonnements.',
    confirmDeleteAppAccount: 'Confirmer la suppression du compte',
    confirmDeleteAppAccountMessage: 'Toutes les données locales de « {user} » seront définitivement supprimées. Continuer ?',
    documentation: 'Guide utilisateur',
    copyAll: 'Tout copier',
    copied: 'Copié !',
    downloadPdf: 'Télécharger le PDF',
    pdfGenerating: 'Génération du PDF…',
    pdfShareTitle: 'Manuel TradeView',
    pdfDownloadFailed: 'Impossible de créer ou enregistrer le PDF. Veuillez réessayer.',
    pdfDownloadTextFallback: 'Échec du PDF ; partage en texte (.txt) avec le même contenu.',
    confirmImport: 'Attention : confirmer l\'écrasement des données ?',
    confirmImportMessage: 'Vous allez importer {fileName}.',
    confirmImportWarning: 'Vos transactions et paramètres actuels seront effacés de façon irréversible.',
    confirmOverride: 'Confirmer l\'écrasement',
    documentationContent: `# Manuel TradeView

> **Confidentialité et sécurité** :
> Ce système adopte une architecture hors ligne. **Toutes les données de transaction sont stockées localement sur votre appareil** (app iOS/Android ou navigateur), sans envoi vers un serveur. **Aucune collecte de données personnelles** — utilisez l'application en toute confiance.

## 1. Présentation
TradeView est un outil de gestion d'actifs pour les marchés boursiers internationaux, qui aide les investisseurs à suivre l'évolution de leurs actifs, calculer les rendements et gérer les flux de trésorerie.

## 2. Démarrage rapide
Suivez cet ordre pour la première configuration (identique au menu hamburger « Comptes → Fonds → Historique → Tableau de bord ») :
1. **Créer un compte** : Allez dans « Comptes » pour ajouter votre compte bancaire ou de courtage.
2. **Importer des fonds** : Allez dans « Fonds », appuyez sur « + Ajouter un enregistrement », choisissez **Dépôt** pour enregistrer salaire ou dépôts.
3. **Ajouter une transaction** : Dans « Historique », appuyez sur « + Ajouter un enregistrement » en haut à droite pour saisir achats/ventes.
4. **Consulter les rapports** : Retournez au « Tableau de bord » pour le résumé ; les **membres** ont aussi graphiques P/L cumulé, allocation, performance marché et carte thermique des dividendes.

## 3. Fonctions détaillées
Les sections ci-dessous suivent l'ordre du menu hamburger (**invité** et **membre** : visibilité légèrement différente ; voir FAQ).

### Tableau de bord
« Tableau de bord » est la page d'accueil par défaut avec cartes résumé et détail des positions. **Membres** : graphiques P/L cumulé, diagramme d'allocation, performance marché et carte thermique des dividendes. En cas de dette sur compte passif, cartes **Crédit & passif** (voir Q&R crédit ci-dessous).

**Carte thermique des dividendes (membres)** : pour un **Réinvestissement des dividendes (DRIP)** en attente, allez dans « Historique » et « + Ajouter un enregistrement » ; **ne pas** appuyer sur « Ajouter » dans la liste en attente (réservé aux dividendes en espèces).

### Historique
Enregistrez achats, ventes, dividendes et transferts d'actions. « + Ajouter un enregistrement » en haut à droite ; « Mise à jour groupée des marchés » pour ajuster plusieurs transactions. Vous pouvez aussi **« Import groupé »** et **« Effacer les transactions filtrées »**.

**Types de transactions**
* **Buy/Sell** : achat/vente général.
* **Réinvestissement des dividendes (DRIP)** : dividende en actions ou réinvestissement ; quantité augmente.
* **Dividende en espèces** : crédit en espèces ; solde augmente.
* **Transfert sortant** : actions transférées hors de ce compte de courtage.
* **Transfert entrant** : actions transférées vers ce compte de courtage.

**Transfert d'actions (Courtier A → Courtier B)**
**Recommandé (en une fois)** : « + Ajouter un enregistrement » → catégorie **Transfert sortant** → compte source (A) → date, marché, symbole, quantité → choisir **Compte cible** (B) → d'abord **« Enregistrer »**, puis dans la fenêtre de confirmation **« Confirmer et enregistrer »**. L'application crée **Transfert sortant et Transfert entrant simultanément** ; l'entrée auto a **frais = 0** — saisissez les frais sur la **sortie**. Le prix par défaut est le coût moyen pour ce compte et ce titre ; utilisez la base de coût, pas le cours du marché.

### Fonds
Appuyez sur « + Ajouter un enregistrement » pour les flux. Catégories :
* **Dépôt** : entrée externe (ex. salaire).
* **Retrait** : sortie (ex. frais de subsistance).
* **Virement** : mouvement entre comptes (ex. banque → courtage).
* **Intérêts** : intérêts sur dépôts ou comptes de courtage.
* **Intérêts d'emprunt** : charge d'intérêts ; sur **Courtage (investissement)**, réduit la trésorerie.

Vous pouvez aussi **« Import en lot »** et **« Effacer les fonds filtrés »**.

### Comptes
Ajoutez ou modifiez comptes bancaires ou de courtage. **Type de compte** : **Courtage (investissement)** ou **Passif (dette)** ; voir Q&R crédit ci-dessous.

### Splits
La page « Splits » enregistre les événements de split. Les transactions conservent quantités et prix saisis ; les splits ajustent positions et P/L à partir de la date d'effet. Si des opérations postérieures utilisent déjà les quantités post-split, ne pas enregistrer à nouveau.

### Rééquilibrage (membres)
« Rééquilibrage » définit les poids cibles : mêmes symboles fusionnés ; cochez **Activer** pour choisir les participants. Poids sauvegardés automatiquement, ou « Réinitialiser aux poids actuels ».

### Simulateur
« Simulateur » compare les rendements attendus de différentes allocations. Saisissez rendements annualisés et poids ; « 🔍 Requête automatique » récupère le CAGR (différent du **Rendement annualisé (XIRR)** du « Tableau de bord »). ⚠️ Performances passées ≠ résultats futurs. Référence uniquement.

### Crédit / passif (Q&R)

Q : Que signifie le **solde** d'un compte passif ?
R : Il représente la **dette actuelle** (ce que vous devez à la banque), pas la trésorerie disponible. Solde zéro = entièrement remboursé.

Q : Comment créer un compte passif ?
R : « Comptes » → **Type de compte** **Passif (dette)** → **Nom du compte**, **Devise**, **Taux annuel (%)**, **Plafond de crédit** (optionnel) → « Ajouter ». Laissez le solde initial à **0**.

Q : Comment enregistrer un décaissement bancaire vers le courtage ?
R : Cela signifie que **la banque verse des fonds empruntés sur votre compte courant de courtage**. Utilisez un **Virement** qui reflète à la fois **l'augmentation de la dette passif** et **l'augmentation de trésorerie courtage** (comptabilisé dans l'investi net).

**Étapes** (« Fonds » → **+ Ajouter un enregistrement**) :
1. **Type de flux** **Virement**
2. **Compte source** **Passif (dette)**
3. **Compte cible** le **Courtage (investissement)** receveur
4. Renseigner **date**, **montant** (capital effectivement versé) ; si **devises différentes**, indiquer le **Taux de change**
5. Confirmer et enregistrer

**Un seul enregistrement suffit**. **Ne pas** ajouter un **Dépôt** sur le passif, sinon la dette est comptée deux fois. Pour « passif → courtage », le formulaire affiche « Tirage crédit : passif → courtage ; compte dans investi net. »

Q : Comment enregistrer le remboursement du capital ?
R : Cela signifie **retirer de la trésorerie courtage pour rembourser le capital** (hors intérêts). Utilisez un **Virement** qui reflète **trésorerie courtage en baisse** et **dette passif en baisse** (comptabilisé dans l'investi net).

**Étapes** (« Fonds » → **+ Ajouter un enregistrement**) :
1. **Type de flux** **Virement**
2. **Compte source** le **Courtage (investissement)** débité
3. **Compte cible** **Passif (dette)**
4. Renseigner **date**, **montant** (**capital uniquement** ; intérêts : question suivante) ; si **devises différentes**, **Taux de change**
5. Confirmer et enregistrer

**Ne pas** utiliser **Retrait** pour le remboursement du capital. Le solde passif ne suit que le **capital** et doit revenir à **0**. Pour « courtage → passif », le formulaire affiche « Remboursement : courtage → passif. »

Q : Où enregistrer les intérêts d'emprunt ?
R : Sur le **Courtage (investissement)**. « Fonds » → **Intérêts d'emprunt** → courtage (liste courtage uniquement, sans passif). Si la banque débite **capital + intérêts** : **deux écritures** — ① **Virement** (courtage → passif) pour le **capital** ; ② **Intérêts d'emprunt** sur le **courtage** pour les intérêts.

Q : Quand le prêt est-il considéré comme soldé ?
R : Lorsque le **solde de dette du compte passif atteint zéro** (solde négatif = intérêts payés en excès, considéré comme soldé). Le total remboursé incluant intérêts dépasse souvent le capital initial — c'est normal.

Q : Supprimer le compte après remboursement ?
R : Non. Compte et historique peuvent rester ; à solde zéro, le « Tableau de bord » masque la section crédit.

Q : Affichage du « Tableau de bord » avec dette ?
R : Si **Solde / Dette** du passif **> 0** (capital dû) : cartes **Crédit & passif**, carte principale **Patrimoine net** (Actif total − Dette totale). Si **= 0** : pas de section crédit, carte principale **Actif total**.

## 4. Questions fréquemment posées (FAQ)

Q : Comment le taux de rendement annualisé est-il calculé ?
R : **Rendement annualisé (XIRR)** du « Tableau de bord » : rendement annualisé pondéré par les flux (dépôts/retraits et actif total actuel), flux irréguliers — différent du CAGR basé sur la seule évolution des prix. « Simulateur » : CAGR en requête automatique.

Q : Comment définir le taux de change ?
R : Taux USD/TWD global en haut à droite, ou taux actuel lors d'un **Virement**.

Q : Différence entre invité et membre ?
R : **Invités** : « Tableau de bord », « Historique », « Fonds », « Comptes », « Splits », « Simulateur » et bases ; cartes résumé et positions. **Membres** : « Rééquilibrage », graphiques P/L cumulé, allocation, performance marché, carte dividendes et **IA Corriger les Actifs Historiques**. Sous « Aide » : **Devenir membre / Gérer l'abonnement** et **Ouvrir les offres d'abonnement**.

Q : Quels sont les avantages de l'adhésion ?
R : Menu « Rééquilibrage », graphiques avancés du tableau de bord et d'allocation, performance de marché, carte thermique des dividendes et analyse historique pour mieux comprendre vos résultats.

Q : Stockage des données et confidentialité ?
R : Comme indiqué, **données entièrement locales**, sans enjeu de données personnelles. Pour éviter perte lors de désinstallation, panne matériel ou effacement, **utilisez régulièrement « Télécharger la sauvegarde (.json) »** ci-dessous.

Q : Impossible de télécharger le fichier de sauvegarde ?
R : **App iOS/Android** : « Télécharger la sauvegarde (.json) » puis partage vers Fichiers, iCloud ou autre cloud. **Web** dans LINE : pop-ups bloqués — Safari ou Chrome.

Q : Pourquoi les prix des actions ne peuvent-ils pas être mis à jour ?
R : Vérifiez le marché ; si incorrect, « Mise à jour groupée des marchés » dans « Historique ».

Q : Pourquoi les prix et taux diffèrent-ils de « IA Mettre à Jour les Prix et Taux de Change » ?
R : Les valeurs web peuvent avoir trois à cinq minutes de retard. Ne pas les utiliser pour acheter/vendre ; référez-vous aux sociétés de bourse. Logiciel de statistique d'actifs uniquement (réserves, voyage, retraite, dépôts, actions/obligations), sans trading. Investissez prudemment et gardez des réserves d'urgence. Merci.

Q : Comment sont calculés **Emprunté / plafond / utilisation** ?
R : Uniquement si **Solde / Dette** du passif **> 0**. **Emprunté** = cette valeur (capital cumulé des flux). **Plafond** = **Plafond de crédit** (même devise). **Utilisation** = emprunté ÷ plafond × 100 % (max. 100 %). Sans plafond, pas de barre de progression.

Q : Comment est calculé **Intérêts estimés mois prochain** ?
R : **Intérêts estimés mois prochain** = solde de dette actuel × taux annuel(%) ÷ 100 ÷ 12. Ex. : 2 000 000 de dette à 2,2 % → 2 000 000 × 2,2 ÷ 100 ÷ 12 ≈ **3 667** / mois. Estimation simple à capital constant ; la banque peut calculer au jour le jour ; @ = taux annuel du compte.

Q : Lien entre crédit, investi net, XIRR et patrimoine net ?
R : **Tirages/remboursements** (passif↔courtage) comptent dans **investi net** et **XIRR** (effet de levier) ; **intérêts d'emprunt** non. **Actif total** = titres + trésorerie courtage ; **Dette totale** = somme des soldes passif (convertis) ; **Patrimoine net** = actif total − dette totale. À solde zéro, cartes crédit et alertes masquées ; historique conservé dans le détail investi net. Interpréter XIRR avec prudence si effet de levier.

Q : Qu'est-ce que la **progression fiscale revenus étrangers** du « Tableau de bord » ?
R : Si **devise de base TWD**, **Statistiques Détaillées** affiche la progression de l'estimation des revenus étrangers (P/L réalisé et dividendes hors marché taïwanais), avec seuils de référence 1 M NT$ (déclaration) et 6,7 M NT$ (abattement de base) pour l'impôt minimum. **Référence fiscale uniquement** — hors autres revenus (assurances, etc.) ; pas un conseil fiscal.

## 5. Avertissements importants

**Avertissement sur les risques d'investissement** :
- ⚠️ Les investissements comportent des risques. Les performances passées ne garantissent pas les résultats futurs.
- Cette application fournit uniquement des fonctions de statistiques et de gestion d'actifs et ne fournit pas de conseils en investissement.
- Cette application ne dispose pas de fonctions de trading de valeurs mobilières et ne peut pas effectuer d'opérations d'achat/vente réelles.
- Toutes les décisions d'investissement doivent être prises par l'utilisateur à sa propre discrétion, et l'utilisateur assume tous les risques associés.
- Les utilisateurs doivent évaluer les risques d'investissement par eux-mêmes et consulter des conseillers financiers professionnels si nécessaire.

**Déclaration de non-conseil en investissement** :
- Toutes les informations, analyses, graphiques et recommandations IA fournis par cette application sont à titre de référence uniquement et ne constituent aucun conseil en investissement.
- Cette application ne garantit aucun résultat d'investissement ou taux de rendement.
- Les utilisateurs doivent prendre des décisions d'investissement basées sur leurs propres circonstances et sont responsables de toutes les décisions d'investissement.

**Précision des données** :
- Les données telles que les prix des actions et les taux de change fournis par cette application peuvent différer des prix du marché réel en raison de retards réseau.
- Les utilisateurs ne doivent pas utiliser les données de cette application comme seule base de référence pour les transactions réelles.
- Il est recommandé de se référer aux cotations en temps réel fournies par les sociétés de valeurs mobilières ou les institutions financières.`,
  },
  transactionForm: {
    ...en.transactionForm,
    addTransaction: 'Ajouter une transaction',
    editTransaction: 'Modifier la transaction',
    date: 'Date de transaction',
    account: 'Compte',
    market: 'Marché',
    ticker: 'Symbole',
    tickerPlaceholder: 'ex. 2330, AAPL',
    category: 'Catégorie',
    price: 'Prix',
    quantity: 'Quantité (actions)',
    quantityFixed: 'Quantité (fixe 1)',
    fees: 'Frais / Taxes',
    note: 'Remarque',
    cancel: 'Annuler',
    saveTransaction: 'Enregistrer',
    updateTransaction: 'Mettre à jour',
    confirmTitle: 'Confirmer la transaction',
    confirmMessage: 'Vérifiez les informations ci-dessous.',
    dateLabel: 'Date :',
    accountLabel: 'Compte :',
    marketLabel: 'Marché :',
    tickerLabel: 'Symbole :',
    typeLabel: 'Type :',
    priceLabel: 'Prix :',
    quantityLabel: 'Quantité :',
    feesLabel: 'Frais :',
    noteLabel: 'Note :',
    totalAmount: 'Montant total :',
    shares: 'actions',
    cashDividendQuantityConfirm: '1 enregistrement',
    backToEdit: 'Retour',
    confirmSave: 'Confirmer et enregistrer',
    previewTitle: 'Aperçu du montant :',
    calculationFormula: 'Formule :',
    calculationMethod: 'Calcul :',
    deductionShort: 'retenue',
    marketTW: 'Taïwan (TW)',
    marketUS: 'États-Unis (US)',
    marketUK: 'Royaume-Uni (UK)',
    marketJP: 'Japon (JP)',
    marketCN: 'Chine (CN)',
    marketSZ: 'Chine Shenzhen (SZ)',
    marketIN: 'Inde (IN)',
    marketCA: 'Actions canadiennes (CA)',
    marketFR: 'Actions francaises (FR)',
    marketHK: 'Actions de Hong Kong (HK)',
    marketKR: 'Corée du Sud (KR)',
    marketDE: 'Allemagne (DE)',
    marketAU: 'Australie (AU)',
    marketSA: 'Arabie saoudite (SA)',
    marketBR: 'Brésil (BR)',
    typeBuy: 'Achat',
    typeSell: 'Vente',
    typeDividend: 'Reinvestissement des dividendes (DRIP)',
    typeCashDividend: 'Dividende en espèces',
    typeTransferIn: 'Transfert entrant',
    typeTransferOut: 'Transfert sortant',
    transferInSectionTitle: 'Informations de transfert entrant',
    targetAccount: 'Compte cible',
    targetAccountPlaceholder: 'Veuillez sélectionner un compte cible...',
    placeholderPrice: 'Prix par action',
    placeholderQuantity: 'Dividende total',
    errorNoAccount: 'Veuillez d\'abord créer un compte.',
    errorNoTargetAccount: 'Veuillez sélectionner un compte cible.',
    errorSameTransferAccount: 'Le compte source et le compte cible ne peuvent pas être identiques.',
    errorInsufficientTransferOutQuantity: 'La quantité sortante dépasse la position disponible',
    availableTransferOutQuantity: 'Disponible : {quantity} {shares}',
    transferInConfirmHint: 'Un enregistrement de transfert entrant sera aussi créé',
    feesShort: 'frais',
    formulaNote: ' (TW arrondi)',
  },
  fundForm: {
    ...en.fundForm,
    addFundRecord: 'Ajouter un flux',
    editFundRecord: 'Modifier le flux',
    date: 'Date du flux',
    type: 'Type de flux',
    account: 'Compte',
    sourceAccount: 'Compte source',
    amount: 'Montant',
    targetAccount: 'Compte cible',
    selectAccount: 'Choisir un compte...',
    exchangeRate: 'Taux de change',
    exchangeRateUSD: 'Taux (TWD/USD)',
    exchangeRateJPY: 'Taux (TWD/JPY)',
    exchangeRateUsdTwd: 'Taux (USD/TWD)',
    exchangeRateUsdJpy: 'Taux (USD/JPY)',
    exchangeRatePair: 'Taux ({quote}/{base})',
    exchangeRateUsdBase: 'Taux (USD/{base})',
    exchangeRateInvalid: 'Impossible de convertir le taux. Vérifiez la devise de base et les taux vs TWD.',
    crossCurrencyTransfer: 'Transfert multi-devises',
    usdConversion: 'Conversion USD',
    jpyConversion: 'Conversion JPY',
    sameCurrencyTransfer: 'Même devise (1.0)',
    fees: 'Frais ({currency})',
    feesNote: 'Frais de virement',
    note: 'Remarque',
    cancel: 'Annuler',
    updateRecord: 'Mettre à jour',
    confirmExecute: 'Confirmer et enregistrer',
    typeDeposit: 'Dépôt',
    typeWithdraw: 'Retrait',
    typeTransfer: 'Virement',
    typeInterest: 'Intérêts',
    confirmTitle: 'Confirmer le flux',
    confirmMessage: 'Vérifiez les informations ci-dessous.',
    dateLabel: 'Date :',
    typeLabel: 'Type :',
    accountLabel: 'Compte :',
    targetAccountLabel: 'Compte cible :',
    amountLabel: 'Montant :',
    exchangeRateLabel: 'Taux :',
    feesLabel: 'Frais :',
    noteLabel: 'Note :',
    totalTWD: 'Total ({currency}) :',
    backToEdit: 'Retour',
    confirmSave: 'Confirmer',
    errorNoAccount: 'Veuillez d\'abord créer un compte.',
    recurringSectionTitle: 'Règles récurrentes & alertes dette',
    recurringRulesTitle: 'Règles récurrentes',
    recurringDayShort: 'Jour {day} · {account} · {amount} {ccy}',
    recurringDisclaimer:
      'Les dépôts ne sont appliqués qu’à l’ouverture de l’app. Les mois manqués sont rattrapés à la prochaine ouverture. Pas d’exécution en arrière-plan.',
    recurringDayOfMonth: 'Jour du mois (1–31)',
    recurringStartMonth: 'Mois de début (facultatif)',
    recurringStartMonthHint: 'Laisser vide pour commencer au mois de création de la règle',
    recurringAddRule: 'Ajouter une règle',
    recurringEditRule: 'Modifier la règle',
    recurringSaveRule: 'Enregistrer la règle',
    recurringDeleteRule: 'Supprimer la règle',
    recurringEnabled: 'Activée',
    recurringLastApplied: 'Dernière application : {period}',
    recurringNoRules: 'Aucune règle récurrente pour le moment',
    recurringDeleteConfirm: 'Supprimer cette règle ? Les dépôts déjà créés restent.',
    recurringInvalidAmount: 'Veuillez sélectionner un compte et saisir un montant valide',
    recurringAmountTwdOptional: 'Montant TWD réel (facultatif)',
    recurringAmountTwdHelp:
      'Devise étrangère : coût estimé par montant × taux + frais. Si le montant du relevé diffère, saisissez-le pour remplacer le calcul. Vide = uniquement le taux.',
    recurringNoteBadge: 'Recurrent',
    recurringKindDeposit: 'Depot recurrent (actifs)',
    recurringLeadDays: 'Delai de rappel (jours)',
    recurringKindDebtAlert: 'Rappel échéance crédit',
    transferDebtDisbursementHint: 'Tirage crédit : passif → courtage ; compte dans investi net.',
    transferDebtRepaymentHint: 'Remboursement : courtage → passif.',
    debtAlertSettingsTitle: 'Alertes dette',
    toggleShowRecurring: 'Afficher règles récurrentes',
    toggleHideRecurring: 'Masquer règles récurrentes',
    toggleShowDebtAlert: 'Afficher alertes dette',
    toggleHideDebtAlert: 'Masquer alertes dette',
    minSafetySpread: 'Marge de sécurité du spread (%)',
    minSafetySpreadHelp:
      'Tant qu’il reste un **solde de dette** sur le passif, si rendement du courtage lié − taux d’emprunt est sous ce seuil, avertissement sur le tableau de bord et ici (indicatif). Masqué à solde zéro. Rappels d’échéance : règle ci-dessus.',
  },
  batchImportModal: {
    title: 'Import groupé de transactions',
    selectAccount: '1. Sélectionner le compte d\'importation',
    selectAccountPlaceholder: '-- Veuillez sélectionner un compte --',
    noAccountsWarning: '⚠️ Import groupé impossible',
    noAccountsMessage: 'Il n\'y a aucun compte dans le système. Veuillez d\'abord aller à la page "Comptes" pour créer un compte, puis revenir pour effectuer l\'import groupé.',
    tabPaste: 'Coller le texte',
    tabUpload: 'Télécharger le fichier CSV',
    pasteLabel: 'Collez ici les données Excel ou de tableau (Format supporté: Date | Achat/Vente/Dividende/Transfert | Symbole | Prix | Quantité | Frais | Montant total)',
    pasteFormat: '💡 Catégorie "Transfert": Une quantité négative est traitée comme un transfert sortant, positive comme un transfert entrant.',
    pasteTip: 'Astuce : collez directement des donnees separees par tabulations depuis Excel.',
    pastePlaceholder:
      '2022/3/30\tAchat\tVT\t103.23\t1.00\t0.00\t103.23\n2025/2/11\tTransfert\tVT\t93.41\t-167.73\t0.00\t15667.99',
    parseButton: 'Analyser le contenu collé',
    uploadLabel: 'Fichiers CSV d\'exportation pris en charge: Charles Schwab, Firstrade',
    uploadSupported: 'Pris en charge : Charles Schwab, Firstrade',
    noFileSelected: 'Aucun fichier sélectionné',
    selectFile: 'Choisir un fichier',
    previewTitle: 'Aperçu des données d\'importation',
    previewSuccess: 'Succès',
    previewSelected: 'Sélectionné',
    previewFailed: 'Échoué',
    previewSelectTransactions: 'Veuillez sélectionner les transactions à importer',
    selectAll: 'Tout sélectionner',
    deselectAll: 'Tout désélectionner',
    allSelected: 'Tout sélectionné',
    selectedCount: '{selected} / {total} sélectionné',
    tableDate: 'Date op.',
    tableAction: 'Operation',
    tableMarket: 'Marché',
    tableSymbol: 'Symbole',
    tableQty: 'Qté',
    tablePrice: 'Prix',
    tableFees: 'Frais',
    tableAmount: 'Montant',
    cancel: 'Annuler',
    confirmImport: 'Confirmer l\'importation',
    confirmImportCount: '({count} lignes)',
    errorNoAccounts: 'Aucun compte disponible, importation impossible',
    errorNoAccountSelected: 'Veuillez d\'abord sélectionner un compte',
    errorNoData: 'Importation impossible: Aucune donnée. Veuillez coller le texte de transaction et analyser, ou télécharger un fichier CSV.',
    errorParseFirst: '⚠️ Veuillez d\'abord cliquer sur le bouton "Analyser le contenu collé", confirmer que le tableau d\'aperçu affiche des données, puis cliquer sur confirmer l\'importation.',
    errorNoTransactionsSelected: 'Veuillez sélectionner au moins une transaction à importer',
    errorParseFailed: 'Impossible d\'analyser les données. {count} lignes ont des erreurs de format, veuillez vérifier.',
    errorParseFailedCount: '{count} lignes en echec',
    errorParseError: 'Erreur d\'analyse: {error}. Veuillez vérifier le format des données.',
  },
  historicalModal: {
    title: 'Prix historiques (Time Machine)',
    selectYearLabel: 'Année',
    selectQuarterLabel: 'Trimestre',
    yearOption: 'Annee {year}',
    noHistoryYears: 'Aucune année',
    fillYearEndButton: '🤖 Compléter les données manquantes {year} Q{quarter}',
    aiSearching: 'Chargement...',
    batchProgress: '⏳ {current}/{total} ({year})',
    batchFetchAll: '🚀 Tout récupérer',
    forceRefresh: 'Forcer la mise à jour (écraser)',
    yearEndDataTitle: 'Données fin {year}',
    exchangeRateLabel: 'Taux (USD/TWD) :',
    colMarket: 'Marché',
    colTicker: 'Symbole',
    colClosePrice: 'Clôture ({year}/12/31)',
    noHoldingsThisYear: 'Aucune position cette année',
    pricePlaceholder: 'Saisir le cours',
    hintTitle: '💡 Remarques :',
    hintBullet1:
      'Premier bouton (🤖 Compléter les données manquantes {year} Q{quarter}) : année et trimestre sélectionnés ; cours/taux de fin de période ; remplit 0 ou vides sans écraser.',
    hintBullet2:
      '🚀 Tout récupérer : 31/12 + fins de trimestre T1–T3 (31/03, 30/06, 30/09) pour des graphiques trimestriels réels.',
    hintBullet3: 'Cochez « Forcer la mise à jour » pour écraser les données existantes.',
    cancel: 'Annuler',
    saveUpdateChart: 'Enregistrer et mettre à jour',
    alertAllComplete: 'Terminé. {count} année(s) traitée(s) (fin d’année + T1–T3).',
    alertNoUpdateNeeded:
      'Toutes les données sont déjà renseignées.\nCochez « Forcer la mise à jour » pour écraser.',
    alertFetchFailed:
      'Impossible de récupérer {count} cours historiques. Vérifiez la connexion.\n\nSymboles : {tickers}',
    alertAiError: 'Échec de la mise à jour. Réessayez plus tard.',
  },
  purchaseModal: {
    title: 'Choisir une formule',
    subtitle: 'Choisissez la formule qui vous convient pour débloquer toutes les fonctionnalités premium',
    onlyAndroid: 'Cette fonctionnalité est disponible uniquement dans l’application Android',
    loadProductsFailed: 'Échec du chargement des produits',
    loginFirst: 'Veuillez vous connecter d’abord',
    purchaseFailed: 'Échec de l’achat',
    monthlyTitle: 'Abonnement mensuel',
    monthlyDesc: 'Facturation mensuelle, résiliable à tout moment',
    monthlyPrice: 'NT$ 60/mois',
    yearlyTitle: 'Abonnement annuel',
    yearlyDesc: 'Facturation annuelle, meilleur rapport qualité-prix',
    yearlyPrice: 'NT$ 590/an',
    loading: 'Chargement...',
    popular: 'POPULAIRE',
    processing: 'Traitement...',
    purchaseNow: 'Acheter maintenant',
    footer:
      'L’abonnement sera activé automatiquement après l’achat. Les abonnements peuvent être annulés à tout moment dans Google Play Store.',
  },
  batchCashFlowModal: {
    title: 'Import groupé des flux de trésorerie',
    guideTitle: 'Instructions :',
    guideBody:
      'Collez les données copiées depuis Excel contenant Date, TWD, USD, Taux, Frais, Total, Compte et Catégorie.',
    guideNoteFx:
      'Remarque : (1) TWD seul : remplir TWD & Total ; USD & Taux vides. (2) TWD→USD transfrontalier : remplir le Taux. (3) USD aux USA (ACH, etc.) : pas de change, Taux vide.',
    columnHeaderExample: 'Date | TWD | USD | Taux | Frais | Total | Compte | Catégorie',
    pasteDemoRow1Account: 'Banque locale',
    pastePlaceholderApprox: '(≈ {approx}, devise de base & cours)',
    parseFailed:
      'Impossible d’analyser les données.\nSuccès : 0\nÉchec : {count}\nVérifiez que le format est séparé par des tabulations (copie directe depuis Excel).',
    unmappedAccounts: 'Veuillez d’abord associer ces comptes :\n{accounts}',
    mappingTitle: '1. Association des comptes',
    mappingDesc: 'Associez les noms de comptes du fichier à vos comptes du système.',
    fileNameLabel: 'Compte du fichier :',
    selectAccount: '-- Sélectionner un compte associé --',
    previewTitle: '2. Aperçu des données',
    successLabel: 'Succès',
    failedLabel: 'Échec',
    failedUnit: 'lignes',
    colDate: 'Date op.',
    colType: 'Catégorie',
    colAmount: 'Montant (USD/TWD)',
    colFee: 'Frais',
    colTwdCost: 'Coût TWD réel',
    colFileAccount: 'Compte du fichier',
    colMappedAccount: 'Compte associé',
    unmapped: 'Non associé',
    cancel: 'Annuler',
    parseData: 'Analyser les données',
    confirmImport: 'Confirmer l’import',
  },
  appMessages: {
    alertTitleInfo: 'Information',
    loginErrorTitle: 'Erreur de connexion',
    loginSuccessTitle: 'Connexion réussie',
    loginFailedTitle: 'Échec de connexion',
    updateSuccessTitle: 'Mise à jour réussie',
    deleteSuccessTitle: 'Suppression réussie',
    restoreSuccessTitle: 'Restauration réussie',
    importFailedTitle: 'Importation échouée',
    downloadErrorTitle: 'Erreur de téléchargement',
    genericErrorTitle: 'Erreur',
    enterEmail: 'Veuillez saisir votre adresse e-mail',
    adminWelcome: 'Bon retour, administrateur !',
    adminPasswordWrong: 'Mot de passe administrateur incorrect',
    guestLoginNotice:
      'Vous êtes maintenant connecté en mode invité.\n\nPour un accès complet, cliquez sur « Mettre à niveau » pour envoyer une demande par e-mail à l’administrateur.',
    contactSubject: 'TradeView Signalement de bug / Commentaires',
    contactBody:
      'Bonjour Admin,\n\nMon compte : {user}\n\nJe souhaite signaler le problème ou la suggestion suivante :\n\n(Veuillez décrire le bug, les étapes ou une suggestion de fonctionnalité)\n\nMerci.',
    updatePriceSuccess: '{count} cours mis à jour',
    updatePriceSuccessWithRate: '{count} cours mis à jour et taux de change synchronisé à {rate}',
    autoUpdateFailed: 'Échec de la mise à jour automatique',
    downloadFailed: 'Téléchargement échoué. Veuillez ouvrir cette page dans un navigateur.',
    shareTitle: 'Fichier de sauvegarde TradeView',
    backupFailed: 'Échec de la sauvegarde : {error}',
    restoreSuccess: 'Données restaurées avec succès !',
    importFailed: 'Importation échouée : format de fichier invalide.',
    txUpdated: 'Transaction mise à jour',
    marketUpdated: 'Paramètres de marché mis à jour pour {count} transactions',
    txDeleted: 'Transaction supprimée',
    txCleared: '✅ {count} transactions supprimées avec succès !',
    accountUpdated: 'Compte « {name} » mis à jour',
    accountDeleted: 'Compte « {name} » supprimé',
    cashFlowUpdated: 'Flux de trésorerie mis à jour',
    cashFlowDeleted: 'Flux de trésorerie supprimé',
    cashFlowCleared: '✅ {count} flux de trésorerie filtré(s) supprimé(s) !',
    historicalSaved: 'Données historiques mises à jour. Les rapports ont été corrigés avec les cours réels.',
    loginPasswordPlaceholder: 'Saisir le mot de passe',
    confirmClearTxTitle: 'Vider les transactions filtrées ?',
    confirmClearTxMessage: 'Cette action supprimera {count} transaction(s) dans le filtre actuel. Elle est irréversible. Assurez-vous d’avoir une sauvegarde.',
    confirmClearAction: 'Confirmer la suppression',
    deleteTxTitle: 'Supprimer la transaction',
    deleteTxMessage: 'Voulez-vous vraiment supprimer cette transaction ?',
    cashFlowDeleteTitle: 'Supprimer le flux de trésorerie',
    unknownAccount: 'Compte inconnu',
    accountLabel: 'Compte :',
    dateLabel: 'Date :',
    typeLabel: 'Type :',
    amountLabel: 'Montant :',
    cashFlowDeleteWarningTitle: '⚠️ Alerte',
    cashFlowDeleteWarningBody:
      'Ce compte possède {count} transactions liées. Supprimer ce flux peut affecter la précision du solde du compte.',
    cashFlowDeleteMessage: 'Voulez-vous vraiment supprimer ce flux de trésorerie ? Cette action est irréversible.',
    confirmDeleteAction: 'Confirmer la suppression',
  },
};
