import type { Translations } from './types';
import { en } from './en';

export const pt: Translations = {
  ...en,
  baseCurrency: { ...en.baseCurrency, TWD: 'Dólar taiwanês', USD: 'Dólar americano', JPY: 'Iene japonês', EUR: 'Euro', GBP: 'Libra esterlina', HKD: 'Dólar de Hong Kong', KRW: 'Won coreano', CAD: 'Dólar canadense', INR: 'Rúpia indiana', CNY: 'Yuan chinês', AUD: 'Dólar australiano', SAR: 'Riyal saudita', BRL: 'Real brasileiro' },
  common: { ...en.common, confirm: 'Confirmar', cancel: 'Cancelar', delete: 'Excluir', edit: 'Editar', save: 'Salvar', close: 'Fechar', loading: 'Carregando...', search: 'Buscar', logoutConfirm: 'Sair?', baseCurrency: 'Moeda base', upgrade: 'Atualizar', footerLocalDataPrivacy: 'Todos os dados de transações ficam armazenados localmente no seu dispositivo para proteger a sua privacidade.' },
  nav: { dashboard: 'Painel', history: 'Histórico', funds: 'Fundos', accounts: 'Contas', rebalance: 'Rebalanceamento', simulator: 'Simulador', splits: 'Desdobramentos', help: 'Sistema', logout: 'Sair' },
  pages: { ...en.pages, dashboard: 'Painel da carteira', history: 'Histórico (transações e fluxo)', funds: 'Gestão de fundos', accounts: 'Gestão de contas', rebalance: 'Rebalanceamento', simulator: 'Simulador de alocação', splits: 'Gestão de desdobramentos', help: 'Sistema e backup' },
  login: { title: 'Login TradeView', subtitle: 'Gestor de Ativos de Investimento', email: 'E-mail', password: 'Senha', login: 'Entrar', privacy: 'Privacidade', privacyDesc: 'Dados armazenados localmente. Sem coleta de dados pessoais.', riskDisclaimer: 'Aviso', riskDisclaimerDesc: 'Investimentos envolvem riscos.' },
  dashboard: {
    ...en.dashboard,
    netCost: 'Investimento líquido',
    totalAssets: 'Patrimônio total',
    totalPL: 'Lucro/Perda',
    annualizedReturn: 'Retorno anualizado (XIRR)',
    detail: 'Detalhe',
    includeCash: 'Incl. Dinheiro',
    detailedStatistics: 'Estatísticas Detalhadas',
    totalCost: 'Custo Total',
    totalPLAmount: 'Valor Total de Lucro/Perda',
    accumulatedCashDividends: 'Dividendos em Dinheiro Acumulados',
    accumulatedStockDividends: 'Dividendos em Ações Acumulados',
    yearDividendTaxTitle: 'Descontos relacionados a dividendos neste ano (referência)',
    yearWithheldNhi: 'Total acumulado de prêmio suplementar NHI (somente registros preenchidos)',
    yearUsWithholding: 'Total acumulado de retenção EUA (somente preenchidos; se vazio, estimado a partir de 30% do líquido)',
    yearUsWithholdingHint: 'Preencher "withholding tax" no registro de dividendo em dinheiro melhora a precisão.',
    annualizedReturnRate: 'Taxa de Retorno Anualizada',
    avgExchangeRate: 'Taxa de Câmbio Média (TWD/USD)',
    currentExchangeRate: 'Taxa de Câmbio Atual',
    totalReturnRate: 'Taxa de Retorno Total',
    assetVsCostTrend: 'Tendência de Ativos vs Custo',
    assetTrendMergedSubtitle:
      'Barras principais à esquerda: custo acumulado e P/L; linhas azul/laranja: ativos totais e estimativa; barras finas à direita: fluxo de entrada, saída, P/L de mercado e renda anual.',
    toggleYearlyFlowBars: 'Barras de fluxo anual',
    yearlyFlowIn: 'Entrada anual',
    yearlyFlowOut: 'Saída anual',
    yearlyMarketPL: 'P/L de mercado anual',
    yearlyIncome: 'Dividendos/Juros anuais',
    aiCorrectHistory: 'AI Corrigir Ativos Históricos',
    marketDistribution: 'Peso por ticker',
    allocation: 'Alocação',
    allocationDonutSubtitle:
      'Anel externo: cada ativo (ex.: VT) como % das posições / Anel interno: ações/títulos (sem caixa)',
    stockBondRatioBadge: 'Ações / títulos',
    legendMarketOuter: 'Posições por ticker (externo)',
    legendStockBondInner: 'Ações/títulos (interno)',
    assetClassOverrideTitle: 'Classificação personalizada ações/títulos (substituições)',
    tickerSymbolLabel: 'Código',
    tickerPlaceholderExamples: 'ex.: AGG / TLT / BND',
    assetClassSelectLabel: 'Classe',
    equityLabelShort: 'Ações',
    bondLabelShort: 'Títulos',
    saveAssetClassOverride: 'Guardar',
    clearTickerOverride: 'Limpar',
    currentOverridesHeading: 'Substituições atuais',
    removeOverrideTitle: 'Clique para remover',
    annualPerformance: 'Desempenho Anual',
    year: 'Ano',
    startAssets: 'Ativos Iniciais',
    annualNetInflow: 'Entrada Líquida Anual',
    endAssets: 'Ativos Finais',
    annualProfit: 'Lucro Anual',
    annualROI: 'ROI Anual',
    brokerageAccounts: 'Lista de contas',
    accountName: 'Nome da conta',
    totalAssetsNT: 'Ativos Totais',
    marketValueNT: 'Valor de Mercado',
    balanceNT: 'Saldo / Dívida',
    balanceColumnTooltip:
      'Corretagem: saldo em caixa; passivo: capital em dívida.',
    profitNT: 'Lucro',
    profitFormulaTooltip: 'P/L Total = Nao Realizado + Realizado + Dividendos/Juros. O realizado considera apenas SELL; transferências são excluídas.',
    accountReturnRateTooltip:
      'Retorno acumulado = P/L ÷ denominador. Entrada líquida; se ≤ 0, custo acumulado. Transferência com valor de mercado: realizado na origem, custo de mercado no destino. Sem posições e caixa ≈ 0 = encerrado; sem posições com caixa = flat.',
    accountClosedBadge: 'Encerrado',
    accountFlatBadge: 'Sem posições',
    unrealizedPL: 'P/L Não Realizado',
    realizedPL: 'P/L Realizado',
    dividendInterest: 'Dividendos/Juros',
    displayCurrency: 'Moeda de Exibição',
    ntd: 'Dólar de Taiwan',
    usd: 'Dólar Americano',
    portfolioHoldings: 'Posições da Carteira',
    mergedDisplay: 'Agrupado (Por Símbolo)',
    detailedDisplay: 'Detalhado (Por Conta)',
    aiUpdatePrices: 'AI Atualizar Preços e Taxas de Câmbio',
    estimatedGrowth8: 'Est. Crescimento de 8%',
    annualizedReturnTarget8: 'Meta 8%',
    chartLoading: 'Carregando gráfico...',
    noChartData: 'Por favor, adicione depósitos de fundos e transações primeiro',
    noHoldings: 'Sem posições',
    noAccounts: 'Sem contas de corretagem. Por favor, adicione contas em Contas.',
    costBreakdown: 'Detalhamento do Custo de Investimento Líquido',
    netInvestedBreakdown: 'Detalhamento do Investimento Líquido',
    calculationFormula: 'Fórmula: Investimento Líquido = Depósitos - Saques',
    formulaNote: 'Nota: Para contas USD, a taxa de câmbio histórica é usada se disponível, caso contrário, a taxa atual das configurações. Transferências e juros não estão incluídos no custo.',
    attention: 'Atenção',
    date: 'Data',
    category: 'Categoria',
    originalAmount: 'Valor original',
    twdCost: 'Custo ({currency})',
    totalNetInvested: 'Total',
    deposit: 'Depósito(+)',
    withdraw: 'Saque(-)',
    fixedTWD: 'Valor TWD fixo',
    historicalRate: 'Taxa histórica',
    currentRate: 'Taxa atual',
    taiwanDollar: 'Dólar taiwanês',
    twdIncludesFee: 'TWD (inclui taxa)',
    aiAdvisor: 'Assistente Gemini AI',
    aiAdvisorDesc: 'Análise de Carteira',
    notInvestmentAdvice: 'Não é aconselhamento de investimento.',
    chartLabels: {
      investmentCost: 'Custo de Investimento',
      accumulatedPL: 'Lucro/Perda Acumulado',
      estimatedAssets: 'Est. Ativos Totais (8%)',
      totalAssets: 'Ativos Totais',
      toDate: ' até agora',
      realData: ' (Preço Real)',
      estimated: ' (Estimado)',
      profit: 'Lucro',
      loss: 'Perda',
      barName: 'Lucro/Perda Acumulado: Verde=Lucro Vermelho=Perda',
      yearlyPeriodRoi: 'Retorno anual',
      chartLegendYearlyPeriodRoi:
        'Linha rosa (eixo direito %): um ponto por ano no Q4 (ano atual: “até hoje” se não houver Q4). Igual à tabela anual.',
    },
    noHoldingsData: 'Sem dados de posições',
    realHistoricalData: 'Dados históricos reais',
    formulaLabel: 'Fórmula: ',
    aiCorrectHistoryTitle: 'Editar manualmente ou usar AI para corrigir preços históricos',
    startAnalysis: 'Iniciar Análise',
    analyzing: 'Analisando...',
    viewCalculationDetails: 'Ver Detalhes',
    riskWarning: 'Aviso de Risco',
    riskWarningDesc: 'Investimentos envolvem riscos. O desempenho passado não garante resultados futuros.',
    chartLegendQuarterSnapshot: '✅ Snapshot fim de trimestre (dados Yahoo)',
    chartLegendLinearInterpolation:
      '⚠️ Interpolação linear — abra Preços históricos para obter dados em falta',
    netWorth: 'Património líquido',
    totalDebt: 'Dívida total',
    leverageNetInvestedNote: 'Investimento líquido pode incluir desembolsos de crédito (~{amount})',
    leverageXirrWarning: 'XIRR inclui fundos emprestados — interprete com cuidado',
    debtDisbursement: 'Desembolso de crédito',
    debtRepayment: 'Amortização de crédito',
    leverageFormulaNote: 'Desembolsos/amortizações (passivo↔corretagem) contam no investimento líquido e XIRR. Juros de empréstimo não.',
    debtAccountsTitle: 'Crédito & dívida',
    creditUsedOfLimit: 'Usado {used} / limite {limit} ({percent}% de utilização)',
    estimatedMonthlyInterest: 'Juros estimados do próximo mês',
    estimatedMonthlyInterestNote: 'Estimativa com saldo atual e taxa anual (um mês)',
  },
  marketChart: {
    title: 'Desempenho por Mercado',
    subtitle: 'Retorno acumulado e peso por mercado',
    cumulativeReturn: 'Retorno acumulado',
    weight: 'Peso',
    value: 'Valor',
    cumulativeReturnShort: 'Retorno',
    weightShort: 'Peso',
    valueShort: 'Valor',
    noData: 'Sem posições',
    ratio: 'Proporção',
  },
  waterfall: {
    title: 'Cascata de Fluxo de Caixa',
    subtitle: 'Valor líquido acumulado: entradas, P&L, dividendos e saídas',
    byYear: 'Por Ano',
    byQuarter: 'Por Trimestre',
    deposit: 'Entradas',
    withdraw: 'Saídas',
    stockPL: 'P&L Ações',
    dividend: 'Dividendos',
    net: 'Líquido Período',
    runningTotal: 'Acumulado',
    periodNet: 'Líquido',
    noData: 'Sem dados de fluxo de caixa',
    plPositive: 'P&L Ações (+)',
    plNegative: 'P&L Ações (−)',
    legendHintStart: 'Valor total da carteira (incl. caixa) no início de cada período.',
    legendHintInflow: 'Depósitos menos levantamentos no período. Azul = entrada líquida, laranja = saída líquida.',
    legendHintDividend: 'Dividendos em numerário e juros creditados no período.',
    legendHintPL: 'Variação do ativo após fluxo líquido e rendimentos; P&L de mercado aproximado. Verde = ganho, vermelho = perda.',
    includingLabel: '(inclui {item})',
  },
  dividendHeatmap: {
    title: 'Mapa de Calor de Dividendos',
    subtitle: 'Cada célula = dividendo mensal. Mais escuro = maior valor.',
    totalDividend: 'Total Dividendos',
    noData: 'Sem registros de dividendos em dinheiro',
    bestMonth: 'Melhor mês',
    less: 'Menos',
    more: 'Mais',
    monthlyBreakdown: 'Detalhes Mensais',
    yearTotal: 'Ano',
    monthTotal: 'Mês',
    recordedLabel: 'Registado',
    pendingLabel: 'Pendente',
  },
  dividendTax: {
    twTooltipTitle: 'Simulação fiscal (referência)',
    estSinglePayout: 'Dividendos estimados por pagamento (último dividendo por ação × posição)',
    estNhiFee: 'Prêmio suplementar NHI estimado (2,11%, simulação)',
    splitHint0050: 'Se os pagamentos forem distribuídos entre corretoras/unidades pagadoras diferentes, o limite por evento pode variar; a retenção real segue a unidade pagadora.',
    usNetTooltipTitle: 'Retenção de dividendos EUA (referência)',
    marketWithholdingRef: 'Retenção de dividendos (estimativa de referência)',
    estGrossPerPayout: 'Bruto estimado por pagamento (por ação × quantidade)',
    estNetAfterWithholding: 'Líquido estimado após retenção (assumindo 30%, aprox. 70%)',
    upcomingTitle: 'Próximos ex-dividendos em 90 dias (Yahoo)',
    upcomingSubtitle: 'Os valores são estimados por "último dividendo em dinheiro por ação × posição atual" e podem diferir do pagamento real.',
    upcomingEmpty: 'Não há agenda elegível de ex-dividendo no momento, ou não há dados públicos disponíveis.',
    upcomingExDate: 'Data ex-dividendo',
    upcomingInferredMonthHint:
      'Este "mês estimado" é inferido pelo padrão histórico de meses de ex-dividendo e ignora meses já registados neste ano. Quando o Yahoo não traz data confirmada para os próximos 90 dias, a data ex-dividendo aparece como "—". O valor continua sendo estimativa, não anúncio oficial.',
    upcomingEstTwd: 'Dividendo estimado (TWD)',
    upcomingEstUsd: 'Líquido estimado (USD)',
    dataFromYahoo: 'Fonte: Yahoo Finance (cache local)',
    disclaimerShort: 'Apenas referência; não é orientação fiscal ou jurídica.',
    usBadgeShort: '70%',
    nhiForecastTag: 'Estimativa: este pagamento único pode acionar cobrança suplementar NHI',
    pendingActualTitle: 'Dividendos realizados pendentes',
    pendingActualSubtitle: 'Ex-dividendos deste ano ainda nao no historico sao listados abaixo. "Adicionar" registra na data de pagamento (visivel na heatmap); "Ocultar" remove o aviso.',
    pendingActualDripHint: 'Para reinvestimento de dividendos (DRIP), use "Adicionar transação" no histórico — não clique em "Adicionar" aqui.',
    pendingActualEmpty: 'Não há dividendos realizados pendentes para complementar.',
    pendingActualLoading: 'A carregar dados realizados...',
    pendingActualAddBtn: 'Adicionar',
    pendingActualAddCol: 'Adicionar ao histórico',
    pendingActualDismissBtn: 'Ocultar',
    pendingActualToggleHide: 'Ocultar lista',
    pendingActualToggleShow: 'Mostrar lista',
    pendingActualEstimatedDate: 'Data estimada de pagamento',
    pendingActualSourceMoneyDj: 'Realizado',
    pendingActualSourceYahoo: 'Complemento Yahoo',
    pendingActualPayDate: 'Data de pagamento',
    pendingActualPerShare: 'Dividendo por ação',
    pendingActualEstAmount: 'Liquido est. (apos impostos)',
    pendingActualAccount: 'Conta de entrada',
    pendingActualNoteTemplate: 'Importação automática: por ação {perShare}, posição {qty}',
    pendingActualConfirmGrossAmount: 'Valor bruto (antes de impostos)',
    pendingActualCompositionEstimated: 'Percentual oficial estimado sujeito ao NHI (dividendos {dividend}% + juros {interest}%)',
    pendingActualNhiEligibleIncome: 'Renda estimada sujeita ao NHI',
    pendingActualCompositionWarning: 'A composição é uma estimativa prévia do FundClear; prevalece o aviso de distribuição.',
    pendingActualCompositionUnavailable: 'A composição oficial do ETF não está disponível; nenhuma taxa NHI foi deduzida automaticamente.',
    pendingActualWireFeeOption: 'Deduzir taxa de transferência de TWD 10',
    pendingActualWireFeeHint: 'A taxa varia por corretora/banco; marque apenas se foi cobrada no depósito.',
    pendingActualWireFeeLabel: 'Taxa de transferência',
  },
  funds: { 
    ...en.funds, 
    title: 'Gestão de fundos',
    operations: 'Operações',
    clearAll: 'Limpar fundos filtrados',
    batchImport: 'Importação em lote',
    addRecord: '+ Adicionar registo',
    filter: 'Filtrar',
    clearFilters: 'Limpar todos os filtros',
    accountFilter: 'Conta',
    typeFilter: 'Tipo',
    dateFrom: 'Data de início',
    dateTo: 'Data de fim',
    allAccounts: 'Todas as contas',
    allTypes: 'Todos os tipos',
    deposit: 'Depósito', 
    withdraw: 'Saque', 
    transfer: 'Transferência', 
    interest: 'Juros',
    loanInterest: 'Juros de empréstimo',
    showRecords: 'A mostrar {count} registos',
    totalRecords: 'Total de {total}',
    last30Days: 'Últimos 30 dias',
    thisYear: 'Este ano',
    confirmClearAll: 'Confirmar limpeza dos registos de fundos filtrados?',
    confirmClearAllMessage: 'Esta operação eliminará {count} registo(s) de depósito, levantamento, transferência e juros no filtro atual, e não pode ser desfeita. Recomenda-se fazer backup dos dados primeiro.',
    confirmClear: 'Confirmar limpeza',
  },
  history: {
    tabTransactions: 'Transações',
    tabTimeline: 'Linha do tempo de posição',
    operations: 'Operações',
    batchUpdateMarket: 'Atualizar mercados em lote',
    clearAll: 'Limpar transações filtradas',
    batchImport: 'Importação em lote',
    addRecord: '+ Adicionar registro',
    filter: 'Filtrar',
    accountFilter: 'Filtrar por conta',
    tickerFilter: 'Filtrar por símbolo',
    dateFrom: 'Data inicial',
    dateTo: 'Data final',
    includeCashFlow: 'Incluir registros de fluxo de caixa',
    clearFilters: 'Limpar todos os filtros',
    showingRecords: 'Exibindo {count} registros',
    totalRecords: 'Total {total}: {transactionCount} transações{hasCashFlow}',
    last30Days: 'Últimos 30 dias',
    thisYear: 'Este ano',
    noTransactions: 'Nenhuma transação',
    noMatchingTransactions: 'Nenhuma transação correspondente encontrada',
    edit: 'Editar',
    delete: 'Excluir',
    includeCashFlowDesc: 'Marque para mostrar depósitos, saques, transferências etc. para ver alterações do saldo',
    hiddenCashFlowRecords: '{count} registros de fluxo de caixa ocultos',
    cashFlowDeposit: 'Depósito',
    cashFlowWithdraw: 'Saque',
    cashFlowTransfer: 'Transferência para fora',
    cashFlowTransferIn: 'Transferência para dentro',
  },
  stockTimeline: {
    ...en.stockTimeline,
    noTransactionsHint: 'Ainda não há transações. Adicione uma transação primeiro.',
    searchPlaceholder: 'Buscar ticker...',
    allMarkets: 'Todos os mercados',
    statusAll: 'Todos',
    statusHolding: 'Em carteira',
    statusClosed: 'Encerrado',
    sortByFirstBuy: 'Ordenar por 1ª compra',
    sortByTicker: 'Ordenar por ticker',
    sortByPLPercent: 'Ordenar por P/L %',
    countUnit: 'ativos',
    symbol: 'Ativo',
    plAndStatus: 'Lucro/Perda / Estado',
    holdingTitle: 'Em carteira',
    closedTitle: 'Encerrado',
    firstBuy: 'Primeira compra',
    lastTrade: 'Última transação',
    holdingDays: 'Dias em carteira',
    avgCost: 'Custo médio',
    currentPrice: 'Preço atual',
    holdingQty: 'Quantidade',
    pl: 'Lucro/Perda',
    fee: 'Taxa',
    noMatches: 'Nenhum ativo corresponde aos filtros',
    legendBuy: 'Compra',
    legendSell: 'Venda',
    legendStockDividend: 'Div. ações',
    legendCashDividend: 'Div. caixa',
    legendTransferIn: 'Transferência entrada',
    legendTransferOut: 'Transferência saída',
    legendHolding: 'Em carteira',
  },
  labels: { ...en.labels, date: 'Data', account: 'Conta', amount: 'Valor', balance: 'Saldo', action: 'Ação', type: 'Tipo', price: 'Preço', quantity: 'Quantidade', currency: 'Moeda', fee: 'Taxa', exchangeRate: 'Câmbio', totalCost: 'Custo total', category: 'Categoria', description: 'Símbolo/Descrição', note: 'Nota' },
  holdings: {
    ...en.holdings,
    portfolioHoldings: 'Posições',
    mergedDisplay: 'Agrupado por símbolo',
    detailedDisplay: 'Detalhe por conta',
    aiUpdatePrices: 'Atualizar preços (IA)',
    aiSearching: 'IA a pesquisar...',
    market: 'Mercado',
    ticker: 'Símbolo',
    quantity: 'Quantidade',
    currentPrice: 'Preço atual',
    weight: 'Peso',
    cost: 'Custo total',
    marketValue: 'Valor de mercado',
    profitLoss: 'L/P',
    annualizedROI: 'Rentabilidade anualizada',
    dailyChange: 'Variação diária',
    avgPrice: 'Preço méd.',
    noHoldings: 'Sem posições. Adicione transações.',
  },
  accounts: { 
    ...en.accounts, 
    addAccount: 'Adicionar conta corretora/banco', 
    accountName: 'Nome da conta',
    accountNamePlaceholder: 'ex. Fubon Securities, Firstrade',
    currency: 'Moeda', 
    currencyTWD: 'Dólar taiwanês',
    currencyUSD: 'Dólar americano',
    currencyJPY: 'Iene japonês',
    currencyEUR: 'Euro',
    currencyGBP: 'Libra esterlina',
    currencyHKD: 'Dólar de Hong Kong',
    currencyKRW: 'Won coreano',
    currencyCNY: 'Yuan chinês',
    currencyINR: 'Rúpia indiana',
    currencyCAD: 'Dólar canadense',
    currencyAUD: 'Dólar australiano', 
    currencySAR: 'Riyal saudita', 
    currencyBRL: 'Real brasileiro',
    subBrokerage: 'Corretor estrangeiro',
    add: 'Adicionar', 
    update: 'Atualizar', 
    editAccount: 'Editar conta',
    balance: 'Saldo', 
    cancel: 'Cancelar',
    updateAccount: 'Atualizar conta',
    confirmDelete: 'Confirmar exclusão da conta',
    confirmDeleteMessage: 'Tem certeza de que deseja excluir "{name}"?',
    deleteWarning: 'Nota: Isso não excluirá os registros de transações históricas desta conta, mas pode causar problemas ao filtrar.',
    deleteAccount: 'Confirmar exclusão',
    cannotDeleteClosedTitle: 'Não é possível excluir conta encerrada',
    cannotDeleteClosedMessage:
      'Esta conta não tem posições nem dinheiro. Excluir deixaria o histórico órfão. Para tirar da lista, oculte-a.',
    hideAccount: 'Ocultar conta',
    hiddenAccountsSection: 'Contas ocultas',
    restoreAccount: 'Restaurar',
    duplicateHiddenNameHint:
      'O nome "{name}" coincide com uma conta oculta. Restaure-a primeiro ou use outro nome.',
    noAccounts: 'Ainda não há contas. Por favor, adicione sua primeira conta corretora acima.',
    cashBalance: 'Saldo em dinheiro',
    editAccountTitle: 'Editar conta',
    accountKind: 'Tipo de conta',
    accountKindBrokerage: 'Corretagem (investimento)',
    accountKindLiability: 'Passivo (dívida)',
    debtKind: 'Tipo de crédito',
    debtKindPersonal: 'Crédito pessoal',
    debtKindMortgage: 'Hipoteca',
    debtKindSecurities: 'Crédito de títulos',
    annualInterestRate: 'Taxa anual (%)',
    creditLimit: 'Limite de crédito',
    linkedBrokerageAccount: 'Corretagem associada',
    debtBalance: 'Principal em dívida',
    liabilityHint: 'Desembolso: transferência passivo → corretagem apenas.',
  },
  debt: {
    paymentAlertTitle: 'Lembrete de pagamento de crédito',
    paymentAlertBody: '« {name} » vence em {days} dia(s) ({date}), cerca de {amount}. Verificar saldo.',
    acknowledgePaid: 'Marcar como pago',
    remindLater: 'Lembrar mais tarde',
    spreadDangerTitle: 'Alerta: margem negativa',
    spreadWarningTitle: 'Alerta: margem baixa',
    spreadBody: '« {name} » retorno {ret}% vs custo do crédito {rate}% (abaixo da margem de segurança).',
    notAdvice: 'Apenas referência, não é aconselhamento de investimento.',
    leverageNetNote: 'Investimento líquido pode incluir empréstimo (~{amount}). Interprete os retornos em separado.',
  },
  stockSplit: {
    title: 'Gestão de desdobramentos',
    hint: 'Os registos de transação mantêm a quantidade e o preço originais do lançamento; o evento de desdobramento apenas ajusta automaticamente posições e P/L a partir da data efetiva. Se operações após a data já estiverem em quantidade pós-desdobramento, não registe novamente.',
    ticker: 'Código da ação',
    tickerPlaceholder: 'Ex.: 2330, AAPL',
    market: 'Mercado',
    effectiveDate: 'Data efetiva',
    sharesFrom: 'Ações antes',
    sharesTo: 'Ações depois',
    splitRatio: 'Proporção',
    note: 'Observação',
    notePlaceholder: 'Ex.: Desdobramento de janeiro de 2024',
    addButton: 'Adicionar evento de desdobramento',
    listTitle: 'Desdobramentos configurados',
    totalCount: 'Total {count}',
    emptyList: 'Sem eventos de desdobramento',
    tickerRequired: 'Informe o código da ação',
    dateRequired: 'Selecione a data efetiva',
    invalidRatio: 'As ações antes/depois devem ser inteiros positivos',
    duplicateError: 'Já existe evento de desdobramento para o mesmo ativo, mercado e data',
    addSuccess: 'Evento de desdobramento adicionado',
    deleteSuccess: 'Evento de desdobramento removido',
    deleteConfirmTitle: 'Confirmar exclusão do evento',
    deleteConfirmMessage: 'Deseja excluir o desdobramento de {ticker} ({date})?',
  },
  rebalance: { 
    ...en.rebalance, 
    title: 'Rebalanceamento', 
    resetToCurrent: 'Redefinir para pesos atuais',
    totalAssets: 'Ativos totais (incl. dinheiro)',
    enable: 'Ativar',
    symbol: 'Símbolo',
    currentPrice: 'Preço atual',
    currentValue: 'Valor atual',
    currentWeight: 'Peso atual',
    targetWeight: 'Peso alvo',
    targetValue: 'Valor alvo',
    adjustAmount: 'Valor de ajuste',
    suggestedAction: 'Ação sugerida',
    cash: 'Dinheiro',
    totalEnabled: 'Itens ativados',
    remainingFunds: 'Fundos restantes',
    notParticipating: 'Não participando',
    accounts: ' contas',
    description: 'Descrição:',
    description1: 'Ações com o mesmo nome são automaticamente mescladas e exibidas. Os pesos alvo são alocados proporcionalmente para cada conta com base nos valores atuais.',
    description2: 'Marque a coluna "Ativar" para selecionar quais ações/títulos precisam ser rebalanceados. Itens não marcados não participarão dos cálculos de rebalanceamento.',
    description3: 'O dinheiro também pode ser marcado. Se marcado, você pode definir manualmente a porcentagem alvo de dinheiro; se não marcado, o dinheiro permanecerá inalterado.',
    description4: 'Os pesos alvo são salvos automaticamente. Se o alvo de dinheiro não for definido manualmente, o sistema calculará automaticamente e alocará a porcentagem restante ao dinheiro; se definido manualmente, seu valor especificado será usado.',
    description5: 'Se a porcentagem alvo de "Dinheiro" for negativa, isso significa que sua alocação alvo de ações excede 100%. Por favor, reduza algumas porcentagens alvo de ações.',
    description6: 'Clique em "Redefinir para pesos atuais" para redefinir rapidamente todos os valores alvo para o status atual.',
    buy: 'Comprar', 
    sell: 'Vender',
    accountLabel: '(Conta)',
    sharesLabel: '(Ações)',
    totalLabel: 'Total geral (',
    accountCount: ' contas',
  },
  simulator: { 
    ...en.simulator, 
    title: 'Simulador de alocação', 
    description: 'Esta ferramenta permite comparar retornos esperados de diferentes alocações de ativos. Insira as taxas de retorno anualizadas desde a criação para várias ações ou ETFs como suposições, e o sistema calculará o desempenho esperado do seu portfólio com base em seus índices de alocação.',
    descriptionWarning: '⚠️ Nota: O desempenho passado não garante resultados futuros. Esta simulação é apenas para referência.',
    basicSettings: 'Configurações básicas',
    initialAmount: 'Valor do investimento inicial',
    investmentYears: 'Anos de investimento',
    regularInvestment: 'Investimento regular (opcional)',
    regularAmount: 'Valor do investimento regular',
    frequency: 'Frequência de investimento',
    monthly: 'Mensal',
    quarterly: 'Trimestral',
    yearly: 'Anual',
    annualTotal: 'Investimento total anual',
    setToZero: 'Definir como 0 para desativar investimento regular',
    importFromHoldings: 'Importar de posições existentes',
    importButton: 'Importar de posições existentes',
    manualAdd: 'Adicionar ativo manualmente',
    ticker: 'Símbolo da ação',
    tickerPlaceholder: 'ex. 0050',
    market: 'Mercado',
    marketTW: 'Taiwanês (TW)',
    marketUS: 'EUA (US)',
    marketUK: 'Reino Unido (UK)',
    marketJP: 'Japão (JP)',
    marketCN: 'China (CN)',
    marketSZ: 'China - Shenzhen (SZ)',
    marketIN: 'Índia (IN)',
    marketCA: 'Canadá (CA)',
    marketFR: 'França (FR)',
    marketHK: 'Hong Kong - HK',
    marketKR: 'Coreia do Sul (KR)',
    marketDE: 'Alemanha (DE)',
    marketAU: 'Austrália (AU)',
    marketSA: 'Arábia Saudita (SA)',
    marketBR: 'Brasil (BR)',
    annualReturn: 'Retorno anualizado (%)',
    allocation: 'Alocação (%)',
    add: 'Adicionar',
    addRow: 'Adicionar linha',
    action: 'Ação',
    delete: 'Excluir',
    addAll: 'Adicionar à lista',
    yearlyInvestment: 'Investimento anual',
    assetList: 'Lista de alocação de ativos',
    autoBalance: 'Balancear automaticamente',
    clearAll: 'Limpar tudo',
    allocationSum: 'Soma da alocação:',
    totalInvested: 'Total investido',
    finalValue: 'Valor final',
    totalReturn: 'Retorno total',
    portfolioAnnualReturn: 'Retorno anual da carteira',
    initial: 'Inicial',
    yearlyProjection: 'Projeção anual',
    yearlyReturnAnalysis: 'Análise anual de retorno',
    detailedYearlyProjection: 'Projeção anual detalhada',
    year: 'Ano',
    assetValue: 'Valor do ativo',
    yearlyReturn: 'Retorno anual',
    cumulativeInvestment: 'Investimento acumulado',
    yearlyReturnRate: 'Taxa de retorno anual',
    allocationWarning: '⚠️ A soma da alocação deve ser 100%, atualmente',
    confirmClear: 'Confirmar limpeza',
    confirmClearMessage: 'Tem certeza de que deseja limpar toda a alocação? Esta ação não pode ser desfeita.',
    dataWarning: '⚠️ Aviso de integridade dos dados:',
    dataWarningDesc: 'Se o resultado ficar muito abaixo do esperado, o histórico do Yahoo Finance pode estar incompleto. Consulte fontes oficiais ou preencha uma taxa anual mais precisa manualmente.',
    autoQuery: '🔍 Consulta automática',
    autoQueryTitle: 'Consulta automática do retorno anualizado desde o IPO',
    querying: 'Consultando',
    cagrExplanation: '📊 Explicação do cálculo do retorno anualizado:',
    cagrFormulaDesc: 'O sistema usa a fórmula CAGR (Taxa de Crescimento Anual Composta):',
    cagrFormula: 'CAGR = ((Preço Atual / Preço Inicial) ^ (1 / Anos)) - 1',
    cagrExample: 'Isso representa a taxa de retorno composta média por ano se comprado no IPO e mantido até agora.',
    cagrExampleValue: 'Exemplo: Ação sobe de 100 para 200 em 5 anos, retorno anualizado é aproximadamente 14,87%',
    errorEnterTicker: 'Informe o código da ação',
    errorEnterAllocation: 'Informe a alocação',
    errorAllocationRange: 'A alocação deve estar entre 0% e 100%',
    errorAllocationSum: 'A soma da alocação não pode ultrapassar 100%',
    errorNoHoldings: 'Não há posições para importar no momento',
    errorEnterTickerFirst: 'Informe o código da ação primeiro',
    errorCannotGetReturn: 'Não foi possível obter o retorno anualizado de {ticker}, informe manualmente',
    errorQueryFailed: 'Falha ao consultar retorno anualizado, informe manualmente',
    close: 'Fechar',
    cancel: 'Cancelar',
    yearPrefix: 'Ano',
    yearSuffix: 'º ano',
    queryingReturn: 'A consultar retorno anualizado de {ticker}...',
  },
  help: {
    dataManagement: 'Gestão de dados',
    export: 'Exportar',
    exportDesc: 'Exportar transações, contas e cotações em JSON. Recomenda-se backup regular.',
    downloadBackup: 'Descarregar backup (.json)',
    import: 'Importar',
    importWarning: 'Atenção: importar um backup substitui todos os dados atuais do sistema.',
    uploadBackup: 'Enviar ficheiro de backup',
    authorizedUsers: 'Utilizadores autorizados',
    authorizedUsersDesc: 'E-mails que podem entrar sem palavra-passe (mascarados por privacidade):',
    emailAccount: 'E-mail',
    status: 'Estado',
    systemAuthorized: 'Autorizado pelo sistema',
    contact: 'Autorização de compra e contacto do administrador',
    contactTitle: 'Gosta do sistema?',
    contactDesc: 'Não membro e quer direitos permanentes, ou sugestões/erros? Contacte o desenvolvedor. Respostas podem demorar.',
    contactEmail: 'Contactar administrador (e-mail)',
    subscription: 'Assinatura de membro (compra no app)',
    subscriptionTitle: 'Tornar-se membro / Gerir assinatura',
    subscriptionDesc: 'Assine pela App Store para desbloquear todas as funcionalidades. Veja planos, compre ou restaure compras aqui.',
    subscribeButton: 'Abrir planos de assinatura',
    deleteAppAccount: 'Excluir conta e dados',
    deleteAppAccountDesc: 'Remove permanentemente o estado de login e todos os dados locais neste dispositivo. Irreversível. Para cancelar assinatura: Ajustes → Assinaturas.',
    confirmDeleteAppAccount: 'Confirmar exclusão da conta',
    confirmDeleteAppAccountMessage: 'Todos os dados locais de «{user}» serão excluídos permanentemente. Continuar?',
    documentation: 'Documentação',
    copyAll: 'Copiar tudo',
    copied: 'Copiado!',
    downloadPdf: 'Descarregar PDF',
    pdfGenerating: 'A gerar PDF…',
    pdfShareTitle: 'Manual TradeView',
    pdfDownloadFailed: 'Não foi possível criar ou guardar o PDF. Tente novamente.',
    pdfDownloadTextFallback: 'Falha no PDF; partilhado como texto (.txt) com o mesmo conteúdo.',
    confirmImport: 'Atenção: confirmar substituição dos dados?',
    confirmImportMessage: 'Está prestes a importar {fileName}.',
    confirmImportWarning: 'Os seus registos e definições atuais serão apagados e não podem ser revertidos.',
    confirmOverride: 'Confirmar substituição',
    documentationContent: `# Manual do utilizador TradeView

> **Privacidade e segurança** :
> Este sistema adopta uma arquitectura offline-first. **Todos os dados de transação ficam armazenados localmente no seu dispositivo** (app iOS/Android ou navegador), sem envio para servidores. **Não há recolha de dados pessoais** — utilize com confiança.

## 1. Introdução
TradeView é uma ferramenta de gestão de activos para mercados de acções de vários países, que ajuda investidores a acompanhar alterações de activos, calcular retornos e gerir fluxos de fundos.

## 2. Início rápido
Siga esta ordem na primeira configuração (igual ao menu hamburger « Contas → Fundos → Histórico → Painel »):
1. **Criar conta**: Vá a « Contas » para adicionar a sua conta bancária ou de corretagem.
2. **Importar fundos**: Vá a « Fundos », toque em « + Adicionar registo », escolha **Depósito** para registar salário ou depósitos.
3. **Adicionar transação**: Em « Histórico », toque em « + Adicionar registro » no canto superior direito para compras/vendas.
4. **Ver relatórios**: Volte ao « Painel » para o resumo; **membros** também têm gráficos P/L acumulado, alocação, desempenho de mercado e mapa de calor de dividendos.

## 3. Funcionalidades detalhadas
As secções abaixo seguem a ordem do menu hamburger (**convidado** e **membro** : visibilidade ligeiramente diferente ; ver FAQ).

### Painel
« Painel » é a página inicial com cartões de resumo e detalhe de posições. **Membros** : gráficos P/L acumulado, diagrama de alocação, desempenho de mercado e mapa de calor de dividendos. Com dívida em conta passivo, cartões **Crédito & dívida** (ver Q&A abaixo).

**Mapa de calor de dividendos (membros)** : para **Reinvestimento de dividendos (DRIP)** pendente, vá a « Histórico » e « + Adicionar registro » ; **não** clique em « Adicionar » na lista pendente (apenas dividendos em dinheiro).

### Histórico
Registe compras, vendas, dividendos e transferências de acções. « + Adicionar registro » no canto superior direito ; « Atualizar mercados em lote » para várias transacções. Também **« Importação em lote »** e **« Limpar transações filtradas »**.

**Tipos de transacções**
* **Buy/Sell** : compra/venda geral.
* **Reinvestimento de dividendos (DRIP)** : dividendo em acções ou reinvestimento ; quantidade aumenta.
* **Dividendo em dinheiro** : crédito em dinheiro ; saldo aumenta.
* **Transferência saída** : acções transferidas desta conta de corretagem.
* **Transferência entrada** : acções transferidas para esta conta de corretagem.

**Transferência de acções (Corretora A → Corretora B)**
**Recomendado (de uma vez)** : « + Adicionar registro » → categoria **Transferência saída** → conta origem (A) → data, mercado, símbolo, quantidade → escolher **Conta de destino da transação** (B) → primeiro **« Salvar »**, depois na janela de confirmação **« Confirmar e salvar »**. A app cria **Transferência saída e Transferência entrada em simultâneo** ; a entrada automática tem **taxas = 0** — taxas na **Saída**. O preço predefinido é o custo médio dessa conta e activo ; use a base de custo, não o preço de mercado.

### Fundos
Toque em « + Adicionar registo » para fluxos de caixa :
* **Depósito** : entrada externa (ex. salário).
* **Levantamento** : saída (ex. despesas de vida).
* **Transferência** : movimento entre contas (ex. banco → corretagem).
* **Juros** : juros em depósitos ou corretagem.
* **Juros de empréstimo** : despesa de juros ; em **Corretagem (investimento)**, reduz caixa.

Também **« Importação em lote »** e **« Limpar fundos filtrados »**.

### Contas
Adicione ou edite contas bancárias ou de corretagem. **Tipo de conta** : **Corretagem (investimento)** ou **Passivo (dívida)** ; ver Q&A de crédito abaixo.

### Desdobramentos
A página « Desdobramentos » regista eventos de split. As transacções mantêm quantidades e preços registados ; os splits ajustam posições e P/L a partir da data efectiva. Se operações posteriores já usam quantidades pós-split, não registe novamente.

### Rebalanceamento (membros)
« Rebalanceamento » define pesos-alvo : símbolos iguais fundidos ; marque **Ativar** para participantes. Pesos guardados automaticamente ou « Redefinir para pesos atuais ».

### Simulador
« Simulador » compara retornos esperados de alocações. Introduza retornos anualizados e pesos ; « 🔍 Consulta automática » obtém CAGR (diferente de **Retorno anualizado (XIRR)** no « Painel »). ⚠️ Desempenho passado ≠ resultados futuros. Apenas referência.

### Crédito / passivo (Q&A)

P: O que significa o **saldo** de uma conta passivo?
R: Representa a **dívida actual** (quanto deve ao banco), não caixa disponível. Saldo zero = totalmente pago.

P: Como criar uma conta passivo?
R: « Contas » → **Tipo de conta** **Passivo (dívida)** → **Nome da conta**, **Moeda**, **Taxa anual (%)**, **Limite de crédito** (opcional) → « Adicionar ». Deixe saldo inicial **0**.

P: Como registar desembolso bancário para corretagem?
R: Significa que **o banco transfere fundos de crédito para a sua conta corrente de corretagem**. Use uma **Transferência** que reflecta **aumento da dívida no passivo** e **aumento de caixa na corretagem** (contabilizado no investimento líquido).

**Passos** (« Fundos » → **+ Adicionar registo**) :
1. **Tipo** **Transferência**
2. **Conta de origem** **Passivo (dívida)**
3. **Conta de destino** a **Corretagem (investimento)** que recebe
4. Preencher **Data**, **Valor** (capital efectivamente transferido) ; se **moedas diferentes**, **Taxa de câmbio**
5. Confirmar e guardar

**Apenas este registo**. **Não** registe **Depósito** extra no passivo, senão a dívida é contada duas vezes. Em « passivo → corretagem », o formulário mostra « Desembolso: passivo → corretagem ; conta no investimento líquido. »

P: Como registar amortização de capital?
R: Significa **retirar caixa da corretagem para pagar capital do empréstimo** (sem juros). Use **Transferência** que reflecte **caixa corretagem a diminuir** e **dívida passivo a diminuir** (contabilizado no investimento líquido).

**Passos** (« Fundos » → **+ Adicionar registo**) :
1. **Tipo** **Transferência**
2. **Conta de origem** a **Corretagem (investimento)** debitada
3. **Conta de destino** **Passivo (dívida)**
4. Preencher **Data**, **Valor** (só **capital** ; juros : pergunta seguinte) ; se **moedas diferentes**, **Taxa de câmbio**
5. Confirmar e guardar

**Não** use **Levantamento** para amortização. O saldo passivo segue só **capital** e deve chegar a **0**. Em « corretagem → passivo », o formulário mostra « Amortização: corretagem → passivo. »

P: Onde registar juros de empréstimo?
R: Na **Corretagem (investimento)**. « Fundos » → **Juros de empréstimo** → corretagem (lista só corretagem, sem passivo). Se o banco debita **capital + juros** : **dois registos** — ① **Transferência** (corretagem → passivo) para **capital** ; ② **Juros de empréstimo** na **corretagem** para juros.

P: Quando o empréstimo está quitado?
R: Quando o **saldo de dívida do passivo chega a zero** (saldo negativo = juros pagos a mais, considerado quitado). O total repago com juros costuma exceder o capital inicial — é normal.

P: Eliminar conta após quitação?
R: Não. Conta e histórico podem permanecer ; com saldo zero, o « Painel » oculta a secção de crédito.

P: Como o « Painel » mostra dívida?
R: Se **Saldo / Dívida** do passivo **> 0** (capital em dívida) : cartões **Crédito & dívida**, cartão principal **Património líquido** (Patrimônio total − Dívida total). Se **= 0** : sem secção crédito, cartão principal **Patrimônio total**.

## 4. Perguntas frequentes (FAQ)

P: Como é calculada a taxa de retorno anualizada?
R: **Retorno anualizado (XIRR)** no « Painel » : retorno anualizado ponderado por fluxos (depósitos/levantamentos e património total actual), fluxos irregulares — diferente do CAGR só de preço. « Simulador » : CAGR na consulta automática.

P: Como definir a taxa de câmbio?
R: Taxa USD/TWD global no canto superior direito, ou taxa actual ao **Transferência**.

P: Diferença entre convidado e membro?
R: **Convidados** : « Painel », « Histórico », « Fundos », « Contas », « Desdobramentos », « Simulador » e bases ; cartões resumo e posições. **Membros** : « Rebalanceamento », gráficos P/L acumulado, alocação, desempenho de mercado, mapa de dividendos e **AI Corrigir Ativos Históricos**. Em « Sistema » : **Tornar-se membro / Gerir assinatura** e **Abrir planos de assinatura**.

P: Quais são os benefícios da adesão?
R: Menu « Rebalanceamento », gráficos avançados do painel e alocação, desempenho de mercado, mapa de calor de dividendos e análise histórica para compreender melhor os resultados.

P: Armazenamento de dados e privacidade?
R: Como indicado, **dados totalmente locais**, sem questões de dados pessoais. Para evitar perda por desinstalação, avaria ou apagamento, **use regularmente « Descarregar backup (.json) »** abaixo.

P: Não consegue descarregar o ficheiro de backup?
R: **App iOS/Android** : « Descarregar backup (.json) » e partilhe para Ficheiros, iCloud ou outra cloud. **Web** no LINE : pop-ups bloqueados — Safari ou Chrome.

P: Por que os preços das acções não actualizam?
R: Verifique o mercado ; se incorrecto, « Atualizar mercados em lote » em « Histórico ».

P: Por que preços e taxas diferem de « AI Atualizar Preços e Taxas de Câmbio »?
R: Valores web podem atrasar três a cinco minutos. Não use para negociar ; referência principal na corretora. Software só para estatística de activos (reserva de emergência, viagem, reforma, depósitos, acções/obrigações), sem trading. Investimentos têm ganhos e perdas — reserve fundos de emergência. Obrigado.

P: Como se calculam **Usado / limite / utilização**?
R: Só se **Saldo / Dívida** do passivo **> 0**. **Usado** = esse valor (capital acumulado dos fluxos). **Limite** = **Limite de crédito** (mesma moeda). **Utilização** = usado ÷ limite × 100 % (máx. 100 %). Sem limite, sem barra de progresso.

P: Como se calcula **Juros estimados do próximo mês**?
R: **Juros estimados do próximo mês** = saldo de dívida actual × taxa anual(%) ÷ 100 ÷ 12. Ex. : 2 000 000 de dívida a 2,2 % → 2 000 000 × 2,2 ÷ 100 ÷ 12 ≈ **3 667** / mês. Estimativa simples com capital constante ; banco pode calcular ao dia ; @ = taxa anual da conta.

P: Relação entre crédito, investimento líquido, XIRR e património líquido?
R: **Desembolsos/amortizações** (passivo↔corretagem) contam em **investimento líquido** e **XIRR** (alavancagem) ; **juros de empréstimo** não. **Patrimônio total** = posições + caixa corretagem ; **Dívida total** = soma saldos passivo (convertidos) ; **Património líquido** = património total − dívida total. Com saldo zero, cartões e alertas ocultos ; histórico mantém-se no detalhe investimento líquido. Interprete XIRR com cuidado se usou alavancagem.

P: O que é **progresso fiscal rendimentos no estrangeiro** no « Painel »?
R: Com **moeda base TWD**, **Estatísticas Detalhadas** mostra progresso da estimativa de rendimentos no estrangeiro (P/L realizado e dividendos fora de Taiwan), com limiares 1 M NT$ (declaração) e 6,7 M NT$ (dedução básica) para imposto mínimo. **Apenas referência fiscal** — exclui outros rendimentos (seguros, etc.) ; não é aconselhamento fiscal.

## 5. Avisos legais importantes

**Aviso de risco de investimento** :
- ⚠️ Os investimentos envolvem riscos. O desempenho passado não garante resultados futuros.
- Esta aplicação fornece apenas funções de estatísticas e gestão de activos e não fornece aconselhamento de investimento.
- Esta aplicação não possui funções de negociação de valores mobiliários e não pode realizar operações de compra/venda reais.
- Todas as decisões de investimento devem ser tomadas pelo utilizador por sua própria conta e risco, e o utilizador assume todos os riscos relacionados.
- Os utilizadores devem avaliar os riscos de investimento de forma independente e consultar consultores financeiros profissionais quando necessário.

**Declaração de não aconselhamento de investimento** :
- Todas as informações, análises, gráficos e recomendações de IA fornecidas por esta aplicação são apenas para referência e não constituem qualquer aconselhamento de investimento.
- Esta aplicação não garante quaisquer resultados de investimento ou taxas de retorno.
- Os utilizadores devem tomar decisões de investimento com base nas suas próprias circunstâncias e são responsáveis por todas as decisões de investimento.

**Precisão dos dados** :
- Dados como preços das acções e taxas de câmbio fornecidos por esta aplicação podem diferir dos preços de mercado reais devido a atrasos na rede.
- Os utilizadores não devem usar os dados desta aplicação como única base de referência para transacções reais.
- É recomendado referir-se a cotações em tempo real fornecidas por empresas de valores mobiliários ou instituições financeiras.`,
  },
  transactionForm: {
    ...en.transactionForm,
    addTransaction: 'Adicionar transação',
    editTransaction: 'Editar transação',
    date: 'Data',
    account: 'Conta',
    market: 'Mercado',
    ticker: 'Símbolo',
    tickerPlaceholder: 'ex: 2330, AAPL',
    category: 'Categoria',
    price: 'Preço',
    quantity: 'Quantidade (ações)',
    quantityFixed: 'Quantidade (fixo 1)',
    fees: 'Taxas / Impostos',
    note: 'Nota',
    cancel: 'Cancelar',
    saveTransaction: 'Salvar',
    updateTransaction: 'Atualizar',
    confirmTitle: 'Confirmar transação',
    confirmMessage: 'Confira as informações abaixo.',
    dateLabel: 'Data:',
    accountLabel: 'Conta:',
    marketLabel: 'Mercado:',
    tickerLabel: 'Símbolo:',
    typeLabel: 'Tipo:',
    priceLabel: 'Preço:',
    quantityLabel: 'Quantidade:',
    feesLabel: 'Taxas:',
    noteLabel: 'Nota:',
    totalAmount: 'Valor total:',
    shares: 'ações',
    cashDividendQuantityConfirm: '1 registro',
    backToEdit: 'Voltar',
    confirmSave: 'Confirmar e salvar',
    previewTitle: 'Pré-visualização do valor:',
    calculationFormula: 'Fórmula:',
    calculationMethod: 'Cálculo:',
    deductionShort: 'retenção',
    marketTW: 'Taiwanês (TW)',
    marketUS: 'EUA (US)',
    marketUK: 'Reino Unido (UK)',
    marketJP: 'Japão (JP)',
    marketCN: 'China (CN)',
    marketSZ: 'China - Shenzhen (SZ)',
    marketIN: 'Índia (IN)',
    marketCA: 'Canadá (CA)',
    marketFR: 'França (FR)',
    marketHK: 'Hong Kong - HK',
    marketKR: 'Coreia do Sul (KR)',
    marketDE: 'Alemanha (DE)',
    marketAU: 'Austrália (AU)',
    marketSA: 'Arábia Saudita (SA)',
    marketBR: 'Brasil (BR)',
    typeBuy: 'Comprar',
    typeSell: 'Vender',
    typeDividend: 'Reinvestimento de dividendos (DRIP)',
    typeCashDividend: 'Dividendo em dinheiro',
    typeTransferIn: 'Transferência entrada',
    typeTransferOut: 'Transferência saída',
    transferInSectionTitle: 'Informações de transferência de ativos (entrada)',
    targetAccount: 'Conta de destino da transação',
    targetAccountPlaceholder: 'Selecione a conta de destino...',
    placeholderPrice: 'Preço por ação',
    placeholderQuantity: 'Dividendo total',
    errorNoAccount: 'Crie uma conta primeiro.',
    errorNoTargetAccount: 'Selecione a conta de destino da transação.',
    errorSameTransferAccount: 'A conta de origem e a conta de destino não podem ser iguais.',
    errorInsufficientTransferOutQuantity: 'A quantidade de saída excede a posição disponível',
    availableTransferOutQuantity: 'Disponível: {quantity} {shares}',
    transferInConfirmHint: 'Um registro de transferência de entrada também será criado',
    feesShort: 'taxas',
    formulaNote: ' (TW arred.)',
  },
  fundForm: {
    ...en.fundForm,
    addFundRecord: 'Adicionar registo de fundos',
    editFundRecord: 'Editar registo de fundos',
    date: 'Data',
    type: 'Tipo',
    account: 'Conta',
    sourceAccount: 'Conta de origem',
    amount: 'Valor',
    targetAccount: 'Conta de destino',
    selectAccount: 'Selecionar conta...',
    exchangeRate: 'Taxa de câmbio',
    exchangeRateUSD: 'Taxa (TWD/USD)',
    exchangeRateJPY: 'Taxa (TWD/JPY)',
    exchangeRateUsdTwd: 'Taxa (USD/TWD)',
    exchangeRateUsdJpy: 'Taxa (USD/JPY)',
    exchangeRatePair: 'Taxa ({quote}/{base})',
    exchangeRateUsdBase: 'Taxa (USD/{base})',
    exchangeRateInvalid: 'Não foi possível converter a taxa. Verifique a moeda base e as taxas vs TWD.',
    crossCurrencyTransfer: 'Transferência multi-moeda',
    usdConversion: 'Conversão USD',
    jpyConversion: 'Conversão JPY',
    sameCurrencyTransfer: 'Mesma moeda (1.0)',
    fees: 'Taxas ({currency})',
    feesNote: 'Taxa de transferência',
    note: 'Nota',
    cancel: 'Cancelar',
    updateRecord: 'Atualizar',
    confirmExecute: 'Confirmar e salvar',
    typeDeposit: 'Depósito',
    typeWithdraw: 'Levantamento',
    typeTransfer: 'Transferência',
    typeInterest: 'Juros',
    confirmTitle: 'Confirmar registo de fundos',
    confirmMessage: 'Confira as informações abaixo.',
    dateLabel: 'Data:',
    typeLabel: 'Tipo:',
    accountLabel: 'Conta:',
    targetAccountLabel: 'Conta de destino:',
    amountLabel: 'Valor:',
    exchangeRateLabel: 'Taxa:',
    feesLabel: 'Taxas:',
    noteLabel: 'Nota:',
    totalTWD: 'Valor total ({currency}):',
    backToEdit: 'Voltar',
    confirmSave: 'Confirmar',
    errorNoAccount: 'Crie uma conta primeiro.',
    recurringSectionTitle: 'Agendamentos e alertas de dívida',
    recurringRulesTitle: 'Regras recorrentes',
    recurringDayShort: 'Dia {day} · {account} · {amount} {ccy}',
    recurringDisclaimer:
      'Os depósitos só são aplicados ao abrir a app. Meses em falta são repostos na próxima abertura. Sem agendamento em segundo plano.',
    recurringDayOfMonth: 'Dia do mês (1–31)',
    recurringStartMonth: 'Mês inicial (opcional)',
    recurringStartMonthHint: 'Deixe vazio para começar no mês em que a regra foi criada',
    recurringAddRule: 'Adicionar regra',
    recurringEditRule: 'Editar regra',
    recurringSaveRule: 'Guardar regra',
    recurringDeleteRule: 'Eliminar regra',
    recurringEnabled: 'Ativa',
    recurringLastApplied: 'Última aplicação: {period}',
    recurringNoRules: 'Ainda sem regras recorrentes',
    recurringDeleteConfirm: 'Eliminar esta regra? Os depósitos já criados mantêm-se.',
    recurringInvalidAmount: 'Selecione uma conta e introduza um montante válido',
    recurringAmountTwdOptional: 'Montante TWD real (opcional)',
    recurringAmountTwdHelp:
      'Moeda estrangeira: custo estimado como montante × taxa + encargos. Se o valor do extrato for diferente, introduza-o para substituir a conversão. Vazio = só pela taxa.',
    recurringNoteBadge: 'Recorrente',
    recurringKindDeposit: 'Depósito recorrente (ativos)',
    recurringKindDebtAlert: 'Lembrete pagamento crédito',
    recurringLeadDays: 'Dias de antecedência',
    transferDebtDisbursementHint: 'Desembolso: passivo → corretagem; conta no investimento líquido.',
    transferDebtRepaymentHint: 'Amortização: corretagem → passivo.',
    debtAlertSettingsTitle: 'Alertas de dívida',
    toggleShowRecurring: 'Mostrar regras recorrentes',
    toggleHideRecurring: 'Ocultar regras recorrentes',
    toggleShowDebtAlert: 'Mostrar alertas de dívida',
    toggleHideDebtAlert: 'Ocultar alertas de dívida',
    minSafetySpread: 'Margem de segurança do spread (%)',
    minSafetySpreadHelp:
      'Com **saldo em dívida** no passivo, se o retorno da corretagem ligada menos a taxa do empréstimo ficar abaixo deste limiar, surge aviso no painel e aqui (informativo). Oculto com saldo zero. Lembretes de pagamento: «Adicionar regra» acima.',
  },
  batchImportModal: {
    title: 'Importação em lote de transações',
    selectAccount: '1. Selecione a conta de importação',
    selectAccountPlaceholder: '-- Selecione uma conta --',
    noAccountsWarning: '⚠️ Não é possível importar em lote',
    noAccountsMessage: 'Não há contas no sistema. Vá em "Contas" e crie uma conta antes de voltar para importar.',
    tabPaste: 'Colar texto (Paste)',
    tabUpload: 'Enviar CSV (Upload)',
    pasteLabel: 'Cole aqui dados do Excel/tabela (formato suportado: Data | Comprar/Vender/Dividendo/Transferência | Código | Preço | Quantidade | Taxas | Valor total)',
    pasteFormat: '💡 Categoria "Transferência": quantidade negativa = saída, positiva = entrada.',
    pasteTip: 'Dica: colar diretamente do Excel em formato tabulado costuma ter melhor precisão.',
    pastePlaceholder:
      '2022/3/30\tComprar\tVT\t103.23\t1.00\t0.00\t103.23\n2025/2/11\tTransferência\tVT\t93.41\t-167.73\t0.00\t15667.99',
    parseButton: 'Analisar conteúdo colado',
    uploadLabel: 'CSV suportado: Charles Schwab, Firstrade',
    uploadSupported: 'Se o CSV não for reconhecido, tente primeiro a aba de colagem de texto.',
    noFileSelected: 'Nenhum arquivo selecionado',
    selectFile: 'Selecionar arquivo',
    previewTitle: 'Pré-visualização dos dados',
    previewSuccess: 'Sucesso',
    previewSelected: 'Selecionado',
    previewFailed: 'Falhou',
    previewSelectTransactions: 'Selecione as transações a importar',
    selectAll: 'Selecionar tudo',
    deselectAll: 'Desmarcar tudo',
    allSelected: 'Tudo selecionado',
    selectedCount: 'Selecionado {selected} / {total}',
    tableDate: 'Data',
    tableAction: 'Ação',
    tableMarket: 'Mercado',
    tableSymbol: 'Símbolo',
    tableQty: 'Qtd',
    tablePrice: 'Preço',
    tableFees: 'Taxas',
    tableAmount: 'Valor',
    cancel: 'Cancelar',
    confirmImport: 'Confirmar importação',
    confirmImportCount: '({count} registos)',
    errorNoAccounts: 'Sem contas, não é possível importar',
    errorNoAccountSelected: 'Selecione uma conta primeiro',
    errorNoData: 'Não é possível importar: sem dados. Cole e analise o texto, ou envie um CSV.',
    errorParseFirst: '⚠️ Clique primeiro em "Analisar conteúdo colado" e confirme que há dados na pré-visualização antes de importar.',
    errorNoTransactionsSelected: 'Selecione pelo menos uma transação para importar',
    errorParseFailed: 'Não foi possível analisar os dados. {count} registos estão em formato inválido.',
    errorParseFailedCount: 'Linhas com falha: {count}',
    errorParseError: 'Erro ao analisar: {error}. Verifique o formato dos dados.',
  },
  historicalModal: {
    title: 'Preços históricos (Time Machine)',
    selectYearLabel: 'Ano',
    selectQuarterLabel: 'Trimestre',
    yearOption: '{year}º ano',
    noHistoryYears: 'Sem anos',
    fillYearEndButton: '🤖 Preencher dados faltantes {year} Q{quarter}',
    aiSearching: 'A carregar...',
    batchProgress: '⏳ {current}/{total} ({year})',
    batchFetchAll: '🚀 Obter todos os anos',
    forceRefresh: 'Forçar nova obtenção (substituir)',
    yearEndDataTitle: 'Dados fim de {year}',
    exchangeRateLabel: 'Taxa (USD/TWD):',
    colMarket: 'Mercado',
    colTicker: 'Símbolo',
    colClosePrice: 'Fecho ({year}/12/31)',
    noHoldingsThisYear: 'Sem posições neste ano',
    pricePlaceholder: 'Introduzir preço',
    hintTitle: '💡 Notas:',
    hintBullet1:
      'Primeiro botão (🤖 Preencher dados faltantes {year} Q{quarter}): ano e trimestre selecionados; cotações/taxas de fim de período; preenche zeros ou vazios sem substituir valores.',
    hintBullet2:
      '🚀 Obter tudo: 31/12 + fins de trimestre T1–T3 (31/03, 30/06, 30/09) para gráficos trimestrais reais.',
    hintBullet3: 'Marque « Forçar nova obtenção » para substituir dados existentes.',
    cancel: 'Cancelar',
    saveUpdateChart: 'Guardar e atualizar gráficos',
    alertAllComplete: 'Concluído. {count} ano(s) processado(s) (fim de ano + T1–T3).',
    alertNoUpdateNeeded:
      'Todos os dados já estão preenchidos.\nMarque « Forçar nova obtenção » para substituir.',
    alertFetchFailed:
      'Não foi possível obter {count} preço(s) histórico(s). Verifique a ligação.\n\nSímbolos: {tickers}',
    alertAiError: 'Falha na atualização. Tente mais tarde.',
  },
  purchaseModal: {
    title: 'Escolher plano de adesão',
    subtitle: 'Escolha um plano adequado para desbloquear todos os recursos premium',
    onlyAndroid: 'Este recurso está disponível apenas no app Android',
    loadProductsFailed: 'Falha ao carregar produtos',
    loginFirst: 'Faça login primeiro',
    purchaseFailed: 'Falha na compra',
    monthlyTitle: 'Assinatura mensal',
    monthlyDesc: 'Cobrança mensal, cancele a qualquer momento',
    monthlyPrice: 'NT$ 60/mês',
    yearlyTitle: 'Assinatura anual',
    yearlyDesc: 'Cobrança anual, melhor custo-benefício',
    yearlyPrice: 'NT$ 590/ano',
    loading: 'A carregar...',
    popular: 'MAIS POPULAR',
    processing: 'A processar...',
    purchaseNow: 'Comprar agora',
    footer:
      'A adesão será ativada automaticamente após a compra. As assinaturas podem ser canceladas a qualquer momento na Google Play Store.',
  },
  batchCashFlowModal: {
    title: 'Importação em lote de fluxo de caixa',
    guideTitle: 'Instruções:',
    guideBody:
      'Cole dados separados por tab do Excel: Data, TWD, USD, Taxa, Comissão, Total, Conta, Categoria. A última coluna é Categoria; a anterior é Conta.',
    guideNoteFx:
      'Nota: (1) Só TWD: preencha TWD e Total; USD e taxa vazios. (2) TWD→USD transfronteiriço: preencha a taxa. (3) USD doméstico EUA (ACH): sem câmbio, taxa vazia.',
    columnHeaderExample: 'Data | TWD | USD | Taxa de câmbio | Comissão | Total | Conta | Categoria',
    pasteDemoRow1Account: 'Banco local',
    pastePlaceholderApprox: '(≈ {approx}; moeda base e taxas)',
    parseFailed:
      'Não foi possível analisar os dados.\nSucesso: 0\nFalha: {count}\nVerifique se o formato está separado por tabulação (copiar diretamente do Excel).',
    unmappedAccounts: 'Associe primeiro estas contas:\n{accounts}',
    mappingTitle: '1. Mapeamento de contas',
    mappingDesc: 'Associe os nomes de conta do ficheiro às contas do sistema.',
    fileNameLabel: 'Conta do ficheiro:',
    selectAccount: '-- Selecionar conta associada --',
    previewTitle: '2. Pré-visualização dos dados',
    successLabel: 'Sucesso',
    failedLabel: 'Falha',
    failedUnit: 'linhas',
    colDate: 'Data',
    colType: 'Categoria',
    colAmount: 'Montante (USD/TWD)',
    colFee: 'Taxa/Comissão',
    colTwdCost: 'Custo real em TWD',
    colFileAccount: 'Conta no ficheiro',
    colMappedAccount: 'Conta associada',
    unmapped: 'Não associado',
    cancel: 'Cancelar',
    parseData: 'Analisar dados',
    confirmImport: 'Confirmar importação',
  },
  appMessages: {
    alertTitleInfo: 'Aviso',
    loginErrorTitle: 'Erro de login',
    loginSuccessTitle: 'Login efetuado',
    loginFailedTitle: 'Falha no login',
    updateSuccessTitle: 'Atualizado',
    deleteSuccessTitle: 'Eliminado',
    restoreSuccessTitle: 'Restauro concluído',
    importFailedTitle: 'Falha na importação',
    downloadErrorTitle: 'Erro de download',
    genericErrorTitle: 'Erro',
    enterEmail: 'Introduza o endereço de e-mail',
    adminWelcome: 'Bem-vindo de volta, administrador!',
    adminPasswordWrong: 'Palavra-passe de administrador incorreta',
    guestLoginNotice:
      'Entrou no modo visitante.\n\nPara acesso completo, clique em "Upgrade" para enviar um pedido por e-mail ao administrador.',
    contactSubject: 'TradeView Relatório de bug / Feedback',
    contactBody:
      'Olá Admin,\n\nA minha conta: {user}\n\nGostaria de reportar o seguinte problema ou sugestão:\n\n(Descreva o bug, passos para reproduzir ou sugestão de funcionalidade)\n\nObrigado.',
    updatePriceSuccess: '{count} preços atualizados',
    updatePriceSuccessWithRate: '{count} preços atualizados e taxa de câmbio sincronizada para {rate}',
    autoUpdateFailed: 'Falha na atualização automática',
    downloadFailed: 'Falha no download. Tente abrir esta página no navegador.',
    shareTitle: 'Ficheiro de backup TradeView',
    backupFailed: 'Falha no backup: {error}',
    restoreSuccess: 'Dados restaurados com sucesso!',
    importFailed: 'Falha na importação: formato de ficheiro inválido.',
    txUpdated: 'Transação atualizada',
    marketUpdated: 'Configurações de mercado atualizadas para {count} transações',
    txDeleted: 'Transação eliminada',
    txCleared: '✅ {count} transações limpas com sucesso!',
    accountUpdated: 'Conta "{name}" atualizada',
    accountDeleted: 'Conta "{name}" eliminada',
    cashFlowUpdated: 'Registo de fluxo de caixa atualizado',
    cashFlowDeleted: 'Registo de fluxo de caixa eliminado',
    cashFlowCleared: '✅ {count} registo(s) de fluxo de caixa filtrado(s) limpos!',
    historicalSaved: 'Dados históricos de ativos atualizados. Relatórios corrigidos com preços reais.',
    loginPasswordPlaceholder: 'Introduzir palavra-passe',
    confirmClearTxTitle: 'Confirmar limpeza das transações filtradas?',
    confirmClearTxMessage: 'Esta ação eliminará {count} transação(ões) no filtro atual. Não pode ser desfeita. Confirme que possui backup.',
    confirmClearAction: 'Confirmar limpeza',
    deleteTxTitle: 'Eliminar transação',
    deleteTxMessage: 'Tem a certeza de que deseja eliminar esta transação?',
    cashFlowDeleteTitle: 'Eliminar registo de fluxo de caixa',
    unknownAccount: 'Conta desconhecida',
    accountLabel: 'Conta:',
    dateLabel: 'Data:',
    typeLabel: 'Tipo:',
    amountLabel: 'Montante:',
    cashFlowDeleteWarningTitle: '⚠️ Atenção',
    cashFlowDeleteWarningBody:
      'Esta conta possui {count} transações relacionadas. Eliminar este registo pode afetar a precisão do saldo da conta.',
    cashFlowDeleteMessage: 'Tem a certeza de que deseja eliminar este registo de fluxo de caixa? Esta ação é irreversível.',
    confirmDeleteAction: 'Confirmar eliminação',
  },
};

