
// 語言類型
export type Language = 'zh-TW' | 'zh-CN' | 'en' | 'ja' | 'ko' | 'de' | 'fr' | 'hi' | 'ar' | 'pt';

/** 語系選項（用於下拉選單） */
export const LANGUAGES: { code: Language; label: string }[] = [
  { code: 'zh-TW', label: '繁' },
  { code: 'zh-CN', label: '简' },
  { code: 'en', label: 'EN' },
  { code: 'ja', label: '日' },
  { code: 'ko', label: '한' },
  { code: 'de', label: 'DE' },
  { code: 'fr', label: 'FR' },
  { code: 'hi', label: 'हि' },
  { code: 'ar', label: 'ع' },
  { code: 'pt', label: 'PT' },
];

// 基準幣別代碼
export type BaseCurrencyCode = 'TWD' | 'USD' | 'JPY' | 'EUR' | 'GBP' | 'HKD' | 'KRW' | 'CAD' | 'INR' | 'CNY' | 'AUD' | 'SAR' | 'BRL';

// 翻譯鍵值類型
export interface Translations {
  // 基準幣顯示名稱
  baseCurrency: {
    TWD: string;
    USD: string;
    JPY: string;
    EUR: string;
    GBP: string;
    HKD: string;
    KRW: string;
    CAD: string;
    INR: string;
    CNY?: string;
    AUD?: string;
    SAR?: string;
    BRL?: string;
  };
  // 通用
  common: {
    confirm: string;
    cancel: string;
    delete: string;
    edit: string;
    save: string;
    close: string;
    loading: string;
    search: string;
    logoutConfirm: string;
    baseCurrency: string;
    upgrade: string;
    /** 頁尾：交易資料僅存本地、隱私說明 */
    footerLocalDataPrivacy: string;
  };
  // 導航
  nav: {
    dashboard: string;
    history: string;
    funds: string;
    accounts: string;
    rebalance: string;
    simulator: string;
    splits: string;
    help: string;
    logout: string;
  };
  // 頁面標題
  pages: {
    dashboard: string;
    history: string;
    funds: string;
    accounts: string;
    rebalance: string;
    simulator: string;
    splits: string;
    help: string;
  };
  // 登入頁
  login: {
    title: string;
    subtitle: string;
    email: string;
    password: string;
    login: string;
    privacy: string;
    privacyDesc: string;
    riskDisclaimer: string;
    riskDisclaimerDesc: string;
  };
  // 儀表板
  dashboard: {
    netCost: string;
    totalAssets: string;
    totalPL: string;
    annualizedReturn: string;
    detail: string;
    includeCash: string;
    detailedStatistics: string;
    totalCost: string;
    totalPLAmount: string;
    accumulatedCashDividends: string;
    accumulatedStockDividends: string;
    yearDividendTaxTitle: string;
    yearWithheldNhi: string;
    yearUsWithholding: string;
    yearUsWithholdingHint: string;
    annualizedReturnRate: string;
    avgExchangeRate: string;
    currentExchangeRate: string;
    totalReturnRate: string;
    assetVsCostTrend: string;
    assetTrendMergedSubtitle: string;
    toggleYearlyFlowBars: string;
    yearlyFlowIn: string;
    yearlyFlowOut: string;
    yearlyMarketPL: string;
    yearlyIncome: string;
    aiCorrectHistory: string;
    marketDistribution: string;
    allocation: string;
    /** 雙層甜甜圈副標：外圓市場 / 內圓股債（不含現金） */
    allocationDonutSubtitle: string;
    /** 內圈選中時徽章 */
    stockBondRatioBadge: string;
    /** 圖例：市場（外圓） */
    legendMarketOuter: string;
    /** 圖例：股債（內圓） */
    legendStockBondInner: string;
    assetClassOverrideTitle: string;
    tickerSymbolLabel: string;
    tickerPlaceholderExamples: string;
    assetClassSelectLabel: string;
    equityLabelShort: string;
    bondLabelShort: string;
    saveAssetClassOverride: string;
    clearTickerOverride: string;
    currentOverridesHeading: string;
    removeOverrideTitle: string;
    annualPerformance: string;
    year: string;
    startAssets: string;
    annualNetInflow: string;
    endAssets: string;
    annualProfit: string;
    annualROI: string;
    brokerageAccounts: string;
    accountName: string;
    totalAssetsNT: string;
    marketValueNT: string;
    balanceNT: string;
    balanceColumnTooltip: string;
    profitNT: string;
    profitFormulaTooltip: string;
    accountReturnRateTooltip: string;
    accountClosedBadge: string;
    /** 無持股但仍有現金 */
    accountFlatBadge: string;
    unrealizedPL: string;
    realizedPL: string;
    dividendInterest: string;
    displayCurrency: string;
    ntd: string;
    usd: string;
    portfolioHoldings: string;
    mergedDisplay: string;
    detailedDisplay: string;
    aiUpdatePrices: string;
    estimatedGrowth8: string;
    /** 年化報酬進度條中央標記（對照 8% 目標） */
    annualizedReturnTarget8: string;
    chartLoading: string;
    noChartData: string;
    noHoldings: string;
    noAccounts: string;
    costBreakdown: string;
    netInvestedBreakdown: string;
    calculationFormula: string;
    formulaNote: string;
    attention: string;
    date: string;
    category: string;
    originalAmount: string;
    twdCost: string;
    totalNetInvested: string;
    deposit: string;
    withdraw: string;
    fixedTWD: string;
    historicalRate: string;
    currentRate: string;
    taiwanDollar: string;
    twdIncludesFee: string;
    chartLabels: {
      investmentCost: string;
      accumulatedPL: string;
      estimatedAssets: string;
      totalAssets: string;
      toDate: string;
      realData: string;
      estimated: string;
      profit: string;
      loss: string;
      barName: string;
      /** 累積損益圖：與年度績效表相同算法之折線（右軸 %） */
      yearlyPeriodRoi: string;
      /** 圖表下方說明：年度報酬折線（僅 Q4／當年至今端點） */
      chartLegendYearlyPeriodRoi: string;
    };
    noHoldingsData: string;
    realHistoricalData: string;
    formulaLabel: string;
    netWorth: string;
    totalDebt: string;
    leverageNetInvestedNote: string;
    leverageXirrWarning: string;
    debtDisbursement: string;
    debtRepayment: string;
    leverageFormulaNote: string;
    debtAccountsTitle: string;
    creditUsedOfLimit: string;
    estimatedMonthlyInterest: string;
    estimatedMonthlyInterestNote: string;
    aiCorrectHistoryTitle: string;
    aiAdvisor: string;
    aiAdvisorDesc: string;
    startAnalysis: string;
    analyzing: string;
    viewCalculationDetails: string;
    riskWarning: string;
    riskWarningDesc: string;
    /** 累積損益圖下方：季末有 Yahoo 真實快照 */
    chartLegendQuarterSnapshot: string;
    /** 累積損益圖下方：線性插值／請至歷史股價補齊 */
    chartLegendLinearInterpolation: string;
    notInvestmentAdvice: string;
  };
  // 各市場績效圖
  marketChart: {
    title: string;
    subtitle: string;
    /** 各市場加總：以 TWD 合計 (市值−成本)/成本，非年化 */
    cumulativeReturn: string;
    weight: string;
    value: string;
    cumulativeReturnShort: string;
    weightShort: string;
    valueShort: string;
    noData: string;
    ratio: string;
  };
  // 資金流瀑布圖
  waterfall: {
    title: string;
    subtitle: string;
    byYear: string;
    byQuarter: string;
    deposit: string;
    withdraw: string;
    stockPL: string;
    dividend: string;
    net: string;
    runningTotal: string;
    periodNet: string;
    noData: string;
    plPositive: string;
    plNegative: string;
    /** 圖例下方說明（與柱狀顏色對應） */
    legendHintStart: string;
    legendHintInflow: string;
    legendHintDividend: string;
    legendHintPL: string;
    includingLabel: string;
  };
  // 股息熱力圖
  dividendHeatmap: {
    title: string;
    subtitle: string;
    totalDividend: string;
    noData: string;
    bestMonth: string;
    less: string;
    more: string;
    monthlyBreakdown: string;
    yearTotal: string;
    monthTotal: string;
    recordedLabel: string;
    pendingLabel: string;
  };
  /** 配息試算：台股二代健保、美股預扣、待補登實績清單 */
  dividendTax: {
    twTooltipTitle: string;
    estSinglePayout: string;
    estNhiFee: string;
    splitHint0050: string;
    usNetTooltipTitle: string;
    marketWithholdingRef: string;
    estGrossPerPayout: string;
    estNetAfterWithholding: string;
    upcomingTitle: string;
    upcomingSubtitle: string;
    upcomingEmpty: string;
    upcomingExDate: string;
    /** 除息日欄為「—」時，推估月來自歷史規律（非 Yahoo 90 天內日曆）；用於表格 tooltip */
    upcomingInferredMonthHint: string;
    upcomingEstTwd: string;
    upcomingEstUsd: string;
    dataFromYahoo: string;
    disclaimerShort: string;
    usBadgeShort: string;
    nhiForecastTag: string;
    pendingActualTitle: string;
    pendingActualSubtitle: string;
    /** 待補登清單：股息再投入請至 nav.history 用 history.addRecord，勿用 pendingActualAddBtn */
    pendingActualDripHint: string;
    pendingActualEmpty: string;
    pendingActualLoading: string;
    pendingActualAddBtn: string;
    pendingActualAddCol: string;
    pendingActualDismissBtn: string;
    pendingActualToggleHide: string;
    pendingActualToggleShow: string;
    pendingActualEstimatedDate: string;
    pendingActualSourceMoneyDj: string;
    pendingActualSourceYahoo: string;
    pendingActualPayDate: string;
    pendingActualPerShare: string;
    pendingActualEstAmount: string;
    pendingActualAccount: string;
    pendingActualNoteTemplate: string;
    pendingActualConfirmGrossAmount: string;
    pendingActualCompositionEstimated: string;
    pendingActualNhiEligibleIncome: string;
    pendingActualCompositionWarning: string;
    pendingActualCompositionUnavailable: string;
    pendingActualWireFeeOption: string;
    pendingActualWireFeeHint: string;
    pendingActualWireFeeLabel: string;
  };
  // 資金管理
  funds: {
    title: string;
    operations: string;
    clearAll: string;
    batchImport: string;
    addRecord: string;
    filter: string;
    clearFilters: string;
    accountFilter: string;
    typeFilter: string;
    dateFrom: string;
    dateTo: string;
    allAccounts: string;
    allTypes: string;
    deposit: string;
    withdraw: string;
    transfer: string;
    interest: string;
    loanInterest: string;
    showRecords: string;
    totalRecords: string;
    last30Days: string;
    thisYear: string;
    confirmClearAll: string;
    confirmClearAllMessage: string;
    confirmClear: string;
  };
  // 交易記錄
  history: {
    tabTransactions: string;
    tabTimeline: string;
    operations: string;
    batchUpdateMarket: string;
    clearAll: string;
    batchImport: string;
    addRecord: string;
    filter: string;
    clearFilters: string;
    accountFilter: string;
    tickerFilter: string;
    dateFrom: string;
    dateTo: string;
    includeCashFlow: string;
    showingRecords: string;
    totalRecords: string;
    last30Days: string;
    thisYear: string;
    noTransactions: string;
    noMatchingTransactions: string;
    edit: string;
    delete: string;
    includeCashFlowDesc: string;
    hiddenCashFlowRecords: string;
    cashFlowDeposit: string;
    cashFlowWithdraw: string;
    cashFlowTransfer: string;
    cashFlowTransferIn: string;
  };
  // 持有時間軸
  stockTimeline: {
    noTransactionsHint: string;
    searchPlaceholder: string;
    allMarkets: string;
    statusAll: string;
    statusHolding: string;
    statusClosed: string;
    sortByFirstBuy: string;
    sortByTicker: string;
    sortByPLPercent: string;
    countUnit: string;
    symbol: string;
    plAndStatus: string;
    holdingTitle: string;
    closedTitle: string;
    firstBuy: string;
    lastTrade: string;
    holdingDays: string;
    avgCost: string;
    currentPrice: string;
    holdingQty: string;
    pl: string;
    fee: string;
    noMatches: string;
    legendBuy: string;
    legendSell: string;
    legendStockDividend: string;
    legendCashDividend: string;
    legendTransferIn: string;
    legendTransferOut: string;
    legendHolding: string;
  };
  // 其他常用文字
  labels: {
    date: string;
    account: string;
    amount: string;
    balance: string;
    action: string;
    type: string;
    price: string;
    quantity: string;
    currency: string;
    fee: string;
    exchangeRate: string;
    totalCost: string;
    category: string;
    description: string;
    note: string;
  };
  // 持倉明細表
  holdings: {
    portfolioHoldings: string;
    mergedDisplay: string;
    detailedDisplay: string;
    aiUpdatePrices: string;
    aiSearching: string;
    market: string;
    ticker: string;
    quantity: string;
    currentPrice: string;
    weight: string;
    cost: string;
    marketValue: string;
    profitLoss: string;
    annualizedROI: string;
    dailyChange: string;
    avgPrice: string;
    noHoldings: string;
  };
  // 帳戶管理
  accounts: {
    addAccount: string;
    accountName: string;
    accountNamePlaceholder: string;
    currency: string;
    currencyTWD: string;
    currencyUSD: string;
    currencyJPY: string;
    currencyEUR: string;
    currencyGBP: string;
    currencyHKD: string;
    currencyKRW: string;
    currencyCNY: string;
    currencyINR: string;
    currencyCAD: string;
    currencyAUD: string;
    currencySAR: string;
    currencyBRL: string;
    subBrokerage: string;
    add: string;
    update: string;
    editAccount: string;
    balance: string;
    cancel: string;
    updateAccount: string;
    confirmDelete: string;
    confirmDeleteMessage: string;
    deleteWarning: string;
    deleteAccount: string;
    cannotDeleteClosedTitle: string;
    cannotDeleteClosedMessage: string;
    hideAccount: string;
    hiddenAccountsSection: string;
    restoreAccount: string;
    duplicateHiddenNameHint: string;
    noAccounts: string;
    cashBalance: string;
    editAccountTitle: string;
    accountKind: string;
    accountKindBrokerage: string;
    accountKindLiability: string;
    debtKind: string;
    debtKindPersonal: string;
    debtKindMortgage: string;
    debtKindSecurities: string;
    annualInterestRate: string;
    creditLimit: string;
    linkedBrokerageAccount: string;
    debtBalance: string;
    liabilityHint: string;
  };
  debt: {
    paymentAlertTitle: string;
    paymentAlertBody: string;
    acknowledgePaid: string;
    remindLater: string;
    spreadDangerTitle: string;
    spreadWarningTitle: string;
    spreadBody: string;
    notAdvice: string;
    leverageNetNote: string;
  };
  stockSplit: {
    title: string;
    hint: string;
    ticker: string;
    tickerPlaceholder: string;
    market: string;
    effectiveDate: string;
    sharesFrom: string;
    sharesTo: string;
    splitRatio: string;
    note: string;
    notePlaceholder: string;
    addButton: string;
    listTitle: string;
    totalCount: string;
    emptyList: string;
    tickerRequired: string;
    dateRequired: string;
    invalidRatio: string;
    duplicateError: string;
    addSuccess: string;
    deleteSuccess: string;
    deleteConfirmTitle: string;
    deleteConfirmMessage: string;
  };
  // 再平衡
  rebalance: {
    title: string;
    resetToCurrent: string;
    totalAssets: string;
    enable: string;
    symbol: string;
    currentPrice: string;
    currentValue: string;
    currentWeight: string;
    targetWeight: string;
    targetValue: string;
    adjustAmount: string;
    suggestedAction: string;
    cash: string;
    totalEnabled: string;
    remainingFunds: string;
    notParticipating: string;
    accounts: string;
    description: string;
    description1: string;
    description2: string;
    description3: string;
    description4: string;
    description5: string;
    description6: string;
    buy: string;
    sell: string;
    accountLabel: string;
    sharesLabel: string;
    totalLabel: string;
    accountCount: string;
  };
  // 模擬器
  simulator: {
    title: string;
    description: string;
    descriptionWarning: string;
    basicSettings: string;
    initialAmount: string;
    investmentYears: string;
    regularInvestment: string;
    regularAmount: string;
    frequency: string;
    monthly: string;
    quarterly: string;
    yearly: string;
    annualTotal: string;
    setToZero: string;
    importFromHoldings: string;
    importButton: string;
    manualAdd: string;
    ticker: string;
    tickerPlaceholder: string;
    market: string;
    marketTW: string;
    marketUS: string;
    marketUK: string;
    marketJP: string;
    marketCN: string;
    marketSZ: string;
    marketIN: string;
    marketCA: string;
    marketFR: string;
    marketHK: string;
    marketKR: string;
    marketDE: string;
    marketAU: string;
    marketSA: string;
    marketBR: string;
    annualReturn: string;
    autoQuery: string;
    querying: string;
    allocation: string;
    add: string;
    assetList: string;
    autoBalance: string;
    clearAll: string;
    allocationSum: string;
    totalInvested: string;
    finalValue: string;
    totalReturn: string;
    portfolioAnnualReturn: string;
    initial: string;
    yearlyProjection: string;
    yearlyReturnAnalysis: string;
    detailedYearlyProjection: string;
    year: string;
    assetValue: string;
    yearlyReturn: string;
    cumulativeInvestment: string;
    yearlyReturnRate: string;
    allocationWarning: string;
    confirmClear: string;
    confirmClearMessage: string;
    dataWarning: string;
    dataWarningDesc: string;
    cagrExplanation: string;
    cagrFormula: string;
    cagrFormulaDesc: string;
    cagrExample: string;
    cagrExampleValue: string;
    errorEnterTicker: string;
    errorEnterAllocation: string;
    errorAllocationRange: string;
    errorAllocationSum: string;
    errorNoHoldings: string;
    errorEnterTickerFirst: string;
    errorCannotGetReturn: string;
    errorQueryFailed: string;
    close: string;
    cancel: string;
    yearPrefix: string;
    yearSuffix: string;
    queryingReturn: string;
    autoQueryTitle: string;
    addRow: string;
    action: string;
    delete: string;
    addAll: string;
    yearlyInvestment: string;
  };
  // 系統說明
  help: {
    dataManagement: string;
    export: string;
    exportDesc: string;
    downloadBackup: string;
    import: string;
    importWarning: string;
    uploadBackup: string;
    authorizedUsers: string;
    authorizedUsersDesc: string;
    emailAccount: string;
    status: string;
    systemAuthorized: string;
    contact: string;
    contactTitle: string;
    contactDesc: string;
    contactEmail: string;
    subscription: string;
    subscriptionTitle: string;
    subscriptionDesc: string;
    subscribeButton: string;
    deleteAppAccount: string;
    deleteAppAccountDesc: string;
    confirmDeleteAppAccount: string;
    confirmDeleteAppAccountMessage: string;
    documentation: string;
    copyAll: string;
    copied: string;
    downloadPdf: string;
    pdfGenerating: string;
    pdfShareTitle: string;
    pdfDownloadFailed: string;
    pdfDownloadTextFallback: string;
    confirmImport: string;
    confirmImportMessage: string;
    confirmImportWarning: string;
    confirmOverride: string;
    documentationContent: string;
  };
  // 交易表單
  transactionForm: {
    addTransaction: string;
    editTransaction: string;
    date: string;
    account: string;
    market: string;
    ticker: string;
    tickerPlaceholder: string;
    category: string;
    price: string;
    quantity: string;
    quantityFixed: string;
    fees: string;
    note: string;
    cancel: string;
    saveTransaction: string;
    updateTransaction: string;
    confirmTitle: string;
    confirmMessage: string;
    dateLabel: string;
    accountLabel: string;
    marketLabel: string;
    tickerLabel: string;
    typeLabel: string;
    priceLabel: string;
    quantityLabel: string;
    feesLabel: string;
    noteLabel: string;
    totalAmount: string;
    shares: string;
    /** 現金股息確認：數量固定為 1 筆交易，非持股股數 */
    cashDividendQuantityConfirm: string;
    backToEdit: string;
    confirmSave: string;
    previewTitle: string;
    calculationFormula: string;
    calculationMethod: string;
    deductionShort: string;
    marketTW: string;
    marketUS: string;
    marketUK: string;
    marketJP: string;
    marketCN: string;
    marketSZ: string;
    marketIN: string;
    marketCA: string;
    marketFR: string;
    marketHK: string;
    marketKR: string;
    marketDE: string;
    marketAU: string;
    marketSA: string;
    marketBR: string;
    typeBuy: string;
    typeSell: string;
    typeDividend: string;
    typeCashDividend: string;
    typeTransferIn: string;
    typeTransferOut: string;
    transferInSectionTitle: string;
    targetAccount: string;
    targetAccountPlaceholder: string;
    placeholderPrice: string;
    placeholderQuantity: string;
    errorNoAccount: string;
    errorNoTargetAccount: string;
    errorSameTransferAccount: string;
    errorInsufficientTransferOutQuantity: string;
    availableTransferOutQuantity: string;
    transferInConfirmHint: string;
    feesShort: string;
    formulaNote: string;
  };
  // 資金管理表單
  fundForm: {
    addFundRecord: string;
    editFundRecord: string;
    date: string;
    type: string;
    account: string;
    sourceAccount: string;
    amount: string;
    targetAccount: string;
    selectAccount: string;
    exchangeRate: string;
    exchangeRateUSD: string;
    exchangeRateJPY: string;
    exchangeRateUsdTwd: string;
    exchangeRateUsdJpy: string;
    exchangeRatePair: string;
    /** 基準幣非 TWD/USD 時，與儀表板一致之 USD/基準幣欄位標籤；{base} 為基準幣代碼 */
    exchangeRateUsdBase: string;
    /** 由 USD/基準幣換算為內部 TWD/帳戶幣失敗 */
    exchangeRateInvalid: string;
    crossCurrencyTransfer: string;
    usdConversion: string;
    jpyConversion: string;
    sameCurrencyTransfer: string;
    fees: string;
    feesNote: string;
    note: string;
    cancel: string;
    updateRecord: string;
    confirmExecute: string;
    typeDeposit: string;
    typeWithdraw: string;
    typeTransfer: string;
    typeInterest: string;
    confirmTitle: string;
    confirmMessage: string;
    dateLabel: string;
    typeLabel: string;
    accountLabel: string;
    targetAccountLabel: string;
    amountLabel: string;
    exchangeRateLabel: string;
    feesLabel: string;
    noteLabel: string;
    totalTWD: string;
    backToEdit: string;
    confirmSave: string;
    errorNoAccount: string;
    recurringSectionTitle: string;
    recurringDisclaimer: string;
    recurringDayShort: string;
    recurringDayOfMonth: string;
    recurringStartMonth: string;
    recurringStartMonthHint: string;
    recurringAddRule: string;
    recurringEditRule: string;
    recurringSaveRule: string;
    recurringDeleteRule: string;
    recurringEnabled: string;
    recurringLastApplied: string;
    recurringNoRules: string;
    recurringDeleteConfirm: string;
    recurringInvalidAmount: string;
    recurringAmountTwdOptional: string;
    /** 定期匯入：實際入帳金額（選填）欄位下方說明（可覆蓋依匯率換算之成本） */
    recurringAmountTwdHelp: string;
    /** 資金列表：僅含內部標記時顯示的短標籤 */
    recurringNoteBadge: string;
    recurringKindDeposit: string;
    recurringKindDebtAlert: string;
    recurringLeadDays: string;
    transferDebtDisbursementHint: string;
    transferDebtRepaymentHint: string;
    /** 資金頁外層卡片標題 */
    recurringRulesTitle: string;
    debtAlertSettingsTitle: string;
    /** 資金頁：展開／收合定期規程區塊 */
    toggleShowRecurring: string;
    toggleHideRecurring: string;
    /** 資金頁：展開／收合負債警示設定 */
    toggleShowDebtAlert: string;
    toggleHideDebtAlert: string;
    minSafetySpread: string;
    minSafetySpreadHelp: string;
  };
  // 批次匯入模組
  batchImportModal: {
    title: string;
    selectAccount: string;
    selectAccountPlaceholder: string;
    noAccountsWarning: string;
    noAccountsMessage: string;
    tabPaste: string;
    tabUpload: string;
    pasteLabel: string;
    pasteFormat: string;
    pasteTip: string;
    /** Tab 分隔之兩列範例（日期｜動作｜代號｜價格｜數量｜手續費｜總金額），動作須與解析器支援之關鍵字一致 */
    pastePlaceholder: string;
    parseButton: string;
    uploadLabel: string;
    uploadSupported: string;
    noFileSelected: string;
    selectFile: string;
    previewTitle: string;
    previewSuccess: string;
    previewSelected: string;
    previewFailed: string;
    previewSelectTransactions: string;
    selectAll: string;
    deselectAll: string;
    allSelected: string;
    selectedCount: string;
    tableDate: string;
    tableAction: string;
    tableMarket: string;
    tableSymbol: string;
    tableQty: string;
    tablePrice: string;
    tableFees: string;
    tableAmount: string;
    cancel: string;
    confirmImport: string;
    confirmImportCount: string;
    errorNoAccounts: string;
    errorNoAccountSelected: string;
    errorNoData: string;
    errorParseFirst: string;
    errorNoTransactionsSelected: string;
    errorParseFailed: string;
    errorParseFailedCount: string;
    errorParseError: string;
  };
  /** 歷史股價校正彈窗（Time Machine） */
  historicalModal: {
    title: string;
    selectYearLabel: string;
    selectQuarterLabel: string;
    /** 下拉選項，{year} */
    yearOption: string;
    noHistoryYears: string;
    /** 按鈕文案，{year} {quarter} */
    fillYearEndButton: string;
    aiSearching: string;
    /** {current} {total} {year} */
    batchProgress: string;
    batchFetchAll: string;
    forceRefresh: string;
    /** {year} */
    yearEndDataTitle: string;
    exchangeRateLabel: string;
    colMarket: string;
    colTicker: string;
    /** {year} */
    colClosePrice: string;
    noHoldingsThisYear: string;
    pricePlaceholder: string;
    hintTitle: string;
    /** {year} {quarter} */
    hintBullet1: string;
    hintBullet2: string;
    hintBullet3: string;
    cancel: string;
    saveUpdateChart: string;
    /** {count} */
    alertAllComplete: string;
    alertNoUpdateNeeded: string;
    /** {count} {tickers} */
    alertFetchFailed: string;
    alertAiError: string;
  };
  // 會員訂閱（iOS 內購）
  subscription: {
    plan: string;
    monthly: string;
    yearly: string;
    periodEndLabel: string;
    lengthLabel: string;
    lengthMonth: string;
    lengthYear: string;
    monthlyDesc: string;
    yearlyDesc: string;
    savePercent: string;
    featureTitle: string;
    feature1: string;
    feature2: string;
    feature3: string;
    feature4: string;
    title: string;
    subtitle: string;
    memberStatus: string;
    inAppOnlyTitle: string;
    inAppOnlyDesc: string;
    loading: string;
    recommended: string;
    currentPlan: string;
    processing: string;
    perYear: string;
    perMonth: string;
    restorePurchases: string;
    termsOfUse: string;
    privacyPolicy: string;
    purchaseSuccess: string;
    purchaseFailedPrefix: string;
    restoreSuccess: string;
    restoreNotFound: string;
    initFailed: string;
    purchaseFailed: string;
    restoreFailed: string;
    becomeMember: string;
  };
  /** 付費方案彈窗（可選，缺省時由元件 fallback） */
  purchaseModal?: {
    title: string;
    subtitle: string;
    onlyAndroid: string;
    loadProductsFailed: string;
    loginFirst: string;
    purchaseFailed: string;
    monthlyTitle: string;
    monthlyDesc: string;
    monthlyPrice: string;
    yearlyTitle: string;
    yearlyDesc: string;
    yearlyPrice: string;
    loading: string;
    popular: string;
    processing: string;
    purchaseNow: string;
    footer: string;
  };
  /** 批次匯入資金彈窗（可選，缺省時由元件 fallback） */
  batchCashFlowModal?: {
    title: string;
    guideTitle: string;
    guideBody: string;
    /** 三列範例對照：純台幣／跨境換匯／美國境內 USD 與匯率欄何時留空 */
    guideNoteFx: string;
    /** Tab 分隔欄位範例（與 Excel 欄位順序一致，供說明區顯示） */
    columnHeaderExample: string;
    /** 範例第一列：帳戶欄示意文字 */
    pasteDemoRow1Account: string;
    /** 基準幣非 TWD 時附加一行：{approx} 為已格式化基準幣金額 */
    pastePlaceholderApprox: string;
    parseFailed: string;
    unmappedAccounts: string;
    mappingTitle: string;
    mappingDesc: string;
    fileNameLabel: string;
    selectAccount: string;
    previewTitle: string;
    successLabel: string;
    failedLabel: string;
    failedUnit: string;
    colDate: string;
    colType: string;
    colAmount: string;
    colFee: string;
    colTwdCost: string;
    colFileAccount: string;
    colMappedAccount: string;
    unmapped: string;
    cancel: string;
    parseData: string;
    confirmImport: string;
  };
  /** App 全域訊息（可選，缺省時由元件 fallback） */
  appMessages?: {
    alertTitleInfo: string;
    loginErrorTitle: string;
    loginSuccessTitle: string;
    loginFailedTitle: string;
    updateSuccessTitle: string;
    deleteSuccessTitle: string;
    restoreSuccessTitle: string;
    importFailedTitle: string;
    downloadErrorTitle: string;
    genericErrorTitle: string;
    enterEmail: string;
    adminWelcome: string;
    adminPasswordWrong: string;
    memberModeLoginSuccess?: string;
    guestModeLoginSuccess?: string;
    guestLoginNotice: string;
    contactSubject: string;
    contactBody: string;
    updatePriceSuccess: string;
    updatePriceSuccessWithRate: string;
    autoUpdateFailed: string;
    downloadFailed: string;
    shareTitle: string;
    backupFailed: string;
    restoreSuccess: string;
    importFailed: string;
    txUpdated: string;
    marketUpdated: string;
    txDeleted: string;
    txCleared: string;
    accountUpdated: string;
    accountDeleted: string;
    cashFlowUpdated: string;
    cashFlowDeleted: string;
    cashFlowCleared: string;
    historicalSaved: string;
    loginPasswordPlaceholder: string;
    confirmClearTxTitle: string;
    confirmClearTxMessage: string;
    confirmClearAction: string;
    deleteTxTitle: string;
    deleteTxMessage: string;
    cashFlowDeleteTitle: string;
    unknownAccount: string;
    accountLabel: string;
    dateLabel: string;
    typeLabel: string;
    amountLabel: string;
    cashFlowDeleteWarningTitle: string;
    cashFlowDeleteWarningBody: string;
    cashFlowDeleteMessage: string;
    confirmDeleteAction: string;
  };
}

// 繁體中文翻譯
